const WAVE_BUILD='ui-mobile-player-v1-20260925';
window.WAVE_BUILD=WAVE_BUILD;
document.documentElement.dataset.build=WAVE_BUILD;
console.info('WAVE BUILD:',WAVE_BUILD);
const MOODS=[['Спокойствие','☁',64,'#7056db'],['Энергия','ϟ',124,'#e8643e'],['Фокус','◎',82,'#318d91'],['Мечтательно','☾',70,'#8b57d8'],['Вечеринка','✦',132,'#d64c9b']];
const GENRE_PAIRS=[
['Поп','Pop'],['Дэнс-поп','Dance Pop'],['Синти-поп','Synthpop'],['Инди-поп','Indie Pop'],['Дрим-поп','Dream Pop'],['Арт-поп','Art Pop'],['K-pop','K-Pop'],['J-pop','J-Pop'],['Гиперпоп','Hyperpop'],['Европоп','Europop'],
['Рок','Rock'],['Альтернатива','Alternative'],['Инди-рок','Indie Rock'],['Классический рок','Classic Rock'],['Хард-рок','Hard Rock'],['Психоделический рок','Psychedelic Rock'],['Прогрессивный рок','Progressive Rock'],['Гаражный рок','Garage Rock'],['Пост-рок','Post-Rock'],['Сёрф-рок','Surf Rock'],['Софт-рок','Soft Rock'],['Панк','Punk'],['Поп-панк','Pop Punk'],['Пост-панк','Post-Punk'],['Хардкор','Hardcore'],['Эмо','Emo'],['Гранж','Grunge'],['Шугейз','Shoegaze'],
['Метал','Metal'],['Хэви-метал','Heavy Metal'],['Трэш-метал','Thrash Metal'],['Дэт-метал','Death Metal'],['Блэк-метал','Black Metal'],['Дум-метал','Doom Metal'],['Пауэр-метал','Power Metal'],['Металкор','Metalcore'],['Ню-метал','Nu Metal'],['Симфоник-метал','Symphonic Metal'],
['Хип-хоп','Hip-Hop/Rap'],['Рэп','Rap'],['Русский рэп','Russian Rap'],['Русский хип-хоп','Russian Hip-Hop'],['Трэп','Trap'],['Дрилл','Drill'],['Бум-бэп','Boom Bap'],['Грайм','Grime'],['Фонк','Phonk'],['Клауд-рэп','Cloud Rap'],['Альтернативный хип-хоп','Alternative Hip-Hop'],['Олдскул-рэп','Old School Rap'],
['Электроника','Electronic'],['EDM','EDM'],['Хаус','House'],['Дип-хаус','Deep House'],['Тек-хаус','Tech House'],['Прогрессив-хаус','Progressive House'],['Эйсид-хаус','Acid House'],['Техно','Techno'],['Детройт-техно','Detroit Techno'],['Минимал-техно','Minimal Techno'],['Транс','Trance'],['Психоделик-транс','Psytrance'],['Дабстеп','Dubstep'],['Драм-н-бейс','Drum & Bass'],['Джангл','Jungle'],['Брейкбит','Breakbeat'],['Гэридж','UK Garage'],['Хардстайл','Hardstyle'],['Хардкор-техно','Hardcore Techno'],['Даунтемпо','Downtempo'],['Трип-хоп','Trip-Hop'],['IDM','IDM'],['Глитч','Glitch'],['Чилвейв','Chillwave'],['Вейпорвейв','Vaporwave'],['Синтвейв','Synthwave'],['Электро','Electro'],['Электросвинг','Electro Swing'],
['R&B','R&B/Soul'],['Соул','Soul'],['Нео-соул','Neo Soul'],['Фанк','Funk'],['Диско','Disco'],['Госпел','Gospel'],['Мотаун','Motown'],
['Джаз','Jazz'],['Свинг','Swing'],['Бибоп','Bebop'],['Фьюжн','Jazz Fusion'],['Смус-джаз','Smooth Jazz'],['Лаунж','Lounge'],['Блюз','Blues'],['Ритм-н-блюз','Rhythm and Blues'],
['Классика','Classical'],['Неоклассика','Neoclassical'],['Барокко','Baroque'],['Опера','Opera'],['Симфоническая','Symphonic'],['Камерная музыка','Chamber Music'],['Фортепиано','Piano'],['Хоровая музыка','Choral'],
['Фолк','Folk'],['Инди-фолк','Indie Folk'],['Фолк-рок','Folk Rock'],['Кантри','Country'],['Блюграсс','Bluegrass'],['Американа','Americana'],['Акустика','Acoustic'],['Авторская песня','Singer-Songwriter'],
['Регги','Reggae'],['Даб','Dub'],['Ска','Ska'],['Дэнсхолл','Dancehall'],['Латино','Latin'],['Реггетон','Reggaeton'],['Сальса','Salsa'],['Бачата','Bachata'],['Самба','Samba'],['Босса-нова','Bossa Nova'],['Танго','Tango'],['Афробит','Afrobeats'],['Амапиано','Amapiano'],['Хайлайф','Highlife'],
['Мировая музыка','World'],['Арабская музыка','Arabic'],['Индийская музыка','Indian'],['Болливуд','Bollywood'],['Африканская музыка','African'],['Кельтская музыка','Celtic'],['Балканская музыка','Balkan'],['Русская музыка','Russian'],
['Лоу-фай','Lo-Fi'],['Эмбиент','Ambient'],['Дарк-эмбиент','Dark Ambient'],['Нью-эйдж','New Age'],['Медитация','Meditation'],['Для сна','Sleep'],['Для фокуса','Focus'],['Для тренировок','Workout'],['Релакс','Relaxation'],['Природа','Nature'],
['Саундтреки','Soundtrack'],['Музыка из игр','Video Game Music'],['Музыка из аниме','Anime'],['Мюзикл','Musical'],['Оркестровая','Orchestral'],['Эпическая музыка','Epic'],['Трейлерная музыка','Trailer Music'],
['Экспериментальная','Experimental'],['Авангард','Avant-Garde'],['Индастриал','Industrial'],['Нойз','Noise'],['Дроун','Drone'],['Чиптюн','Chiptune'],['8-бит','8-Bit'],['Споукен-ворд','Spoken Word'],['Подкасты','Podcasts'],['Комедия','Comedy'],['Детская музыка','Kids']];
const GENRES=GENRE_PAIRS.map(x=>x[0]);
const TITLES=['Неоновый дождь','Выше облаков','Тихий город','После полуночи','Новый горизонт','Тёплый свет','Импульс','Вне времени','Линии'];
const ARTISTS=['Luma','Northline','Mira Vee','Slow Frames','Nova Room','Aster','Low Tide'];
let state=JSON.parse(localStorage.getItem('waveState')||'null')||{mood:'Спокойствие',genres:['Поп','Электроника'],discovery:50,likes:[],history:[]};
state.likes ||= []; state.history ||= []; state.dislikes ||= []; state.taste ||= {genres:{},artists:{}};state.trackStats||={};
state.crossfadeEnabled ??= true;state.crossfadeDuration=Number.isFinite(+state.crossfadeDuration)?Math.max(0,Math.min(10,+state.crossfadeDuration)):5;
state.repeatCurrent ??= false;
state.genreUsageCount||={};state.recentGenreSelections||=[];state.taste.subgenres||={};
state.genreIntentStrength=Number.isFinite(+state.genreIntentStrength)?+state.genreIntentStrength:(state.genres.length?.7:0);
if(!state.genreTasteMigrated){let migrated={};Object.entries(state.taste.genres||{}).forEach(([genre,value])=>{let family=WaveGenre.normalizeGenre(genre).normalizedGenre;migrated[family]=(migrated[family]||0)+value});state.taste.genres={...state.taste.genres,...migrated};state.genreTasteMigrated=true}
let waveSession=WaveRecommendation.createSession(state.waveSession||{currentMood:state.mood,noveltyLevel:state.discovery/100});
let queue=[],index=0,catalog=[],catalogLoadedAt=0,playing=false,elapsed=0,timer,audio,media,playbackRetryCount=0,playbackStoppedOnError=false,playedSinceCatalogRefresh=0,catalogRefreshInFlight=false;
let failedTrackIds=new Set();
const MAX_PLAYBACK_RETRIES=2;
const MAX_STREAM_VALIDATION_CANDIDATES=8;
const PLAYABLE_CACHE_TTL=12*60*1000;
let verifiedPlayableTrackIds=new Map(),selectionInProgress=false;
window.__lastWaveSelections=[];
let genreQuery='';
let searchResults=[],searchTimer,searchRequest=0;
const sourceManager=new WaveSourceManager();
const PLAYER_STATES={IDLE:'IDLE',LOADING:'LOADING',PLAYING:'PLAYING',PAUSED:'PAUSED',ERROR:'ERROR'};
let playerState=null,playbackBuffer={current:null,next:null,backupNext:null},preloadMedia=null,preloadReady=false,preloadRequestId=0,bufferFillPromise=null,nextStartedAt=0,crossfadeInProgress=false,crossfadeFrame=0;
const tabChannel='BroadcastChannel'in window?new BroadcastChannel('wave-player'):null;
const $=s=>document.querySelector(s), save=()=>{state.waveSession=waveSession;localStorage.setItem('waveState',JSON.stringify(state))};
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
function paintRange(input){input.style.setProperty('--value',`${(input.value-input.min)/(input.max-input.min)*100}%`)}
document.querySelectorAll('input[type="range"]').forEach(input=>{paintRange(input);input.addEventListener('input',()=>paintRange(input))});
function choices(){
  let genreScroll=$('#genres')?.scrollTop||0;
  $('#moods').innerHTML=MOODS.map(m=>`<button class="mood ${state.mood===m[0]?'selected':''}" data-mood="${m[0]}" aria-pressed="${state.mood===m[0]}"><b>${m[1]}</b><span>${m[0]}</span></button>`).join('');
  let visible=GENRES.filter(g=>g.toLocaleLowerCase('ru').includes(genreQuery)).sort((a,b)=>Number(state.genres.includes(b))-Number(state.genres.includes(a))||(state.recentGenreSelections.indexOf(a)<0?999:state.recentGenreSelections.indexOf(a))-(state.recentGenreSelections.indexOf(b)<0?999:state.recentGenreSelections.indexOf(b))||(state.genreUsageCount[b]||0)-(state.genreUsageCount[a]||0));
  $('#genres').innerHTML=visible.length?visible.map(g=>`<button class="genre ${state.genres.includes(g)?'selected':''}" data-genre="${g}" aria-pressed="${state.genres.includes(g)}">${g}</button>`).join(''):'<span class="genre-empty">Такого жанра пока нет</span>';
  $('#genreCount').textContent=genreQuery?`найдено: ${visible.length}`:`выбирай несколько · ${GENRES.length} направлений`;
  $('#genres').scrollTop=genreScroll;
  $('#hint').textContent=`${state.mood} · ${state.genres.join(', ')||'Любые жанры'}`;
}
$('#moods').onclick=e=>{let b=e.target.closest('[data-mood]');if(b&&state.mood!==b.dataset.mood){state.mood=b.dataset.mood;WaveRecommendation.updateWavePreferences(waveSession,{mood:state.mood});save();choices();invalidateNextBuffer('mood');void loadCatalog(true);toast('Настроение обновлено — повлияет на следующий трек')}};
$('#genres').onclick=e=>{let b=e.target.closest('[data-genre]');if(!b)return;let g=b.dataset.genre,adding=!state.genres.includes(g);state.genres=adding?[...state.genres,g]:state.genres.filter(x=>x!==g);state.genreIntentStrength=state.genres.length?1:0;if(adding){state.genreUsageCount[g]=(state.genreUsageCount[g]||0)+1;state.recentGenreSelections=[g,...state.recentGenreSelections.filter(x=>x!==g)].slice(0,20)}save();choices();void loadCatalog(true);toast('Жанры обновлены — повлияют на следующий трек')};
$('#genreSearch').oninput=e=>{genreQuery=e.target.value.trim().toLocaleLowerCase('ru');choices()};
function renderMusicResults(message=''){
  let box=$('#musicResults');
  if(message){box.innerHTML=`<div class="search-message">${escapeHtml(message)}</div>`;box.classList.add('open');return}
  if(!searchResults.length){box.classList.remove('open');box.innerHTML='';return}
  box.innerHTML=searchResults.map((t,i)=>`<button class="music-result" data-search-index="${i}"><img src="${escapeHtml(t.artwork||'wave-icon.svg')}" alt=""><span><strong>${escapeHtml(t.title)}</strong><small>${escapeHtml(t.artist||'Исполнитель')}${t.album?` · Альбом: ${escapeHtml(t.album)}`:''}</small></span><i>▶</i></button>`).join('');box.classList.add('open')
}
async function searchMusic(value){
  let query=value.trim(),request=++searchRequest;if(query.length<2){searchResults=[];renderMusicResults();return}
  renderMusicResults('Ищем треки и альбомы…');
  try{let results=await sourceManager.searchTracks(query);if(request!==searchRequest)return;searchResults=results.slice(0,30);renderMusicResults(searchResults.length?'':'Ничего не найдено')}
  catch{if(request===searchRequest){searchResults=[];renderMusicResults('Поиск временно недоступен')}}
}
$('#musicSearch').oninput=e=>{clearTimeout(searchTimer);let value=e.target.value;if(value.trim().length<2){searchRequest++;searchResults=[];renderMusicResults();return}searchTimer=setTimeout(()=>searchMusic(value),320)};
$('#musicResults').onclick=async e=>{let button=e.target.closest('[data-search-index]');if(!button||selectionInProgress)return;let track=searchResults[+button.dataset.searchIndex];if(!track)return;selectionInProgress=true;let m=MOODS.find(x=>x[0]===state.mood)||MOODS[0],candidate=normalize({...track,_reason:track.album_name?`Альбом: ${track.album_name}`:'Найдено через поиск'},m),selected=WaveRecommendation.scoreTrack(candidate,recommendationContext());catalog=[candidate,...searchResults.map(t=>normalize(t,m)),...catalog].filter((t,i,a)=>a.findIndex(x=>WaveRecommendation.idOf(x)===WaveRecommendation.idOf(t))===i);pause();$('#player').classList.add('visible');$('#miniPlayer').classList.add('visible');document.querySelectorAll('[data-player-title]').forEach(x=>x.textContent='Подбираем доступный трек…');document.querySelectorAll('[data-player-artist]').forEach(x=>x.textContent='Проверяем источник аудио');let playable;try{playable=await validateCandidate(selected,1)}finally{selectionInProgress=false}if(!playable)return toast('Этот аудиопоток недоступен');queue=[selectedTrack(selected,playable)];index=0;load();void play();$('#musicResults').classList.remove('open');closeSearch()};
document.addEventListener('click',e=>{if(!e.target.closest('.music-search'))$('#musicResults').classList.remove('open')});
$('#discovery').value=state.discovery;paintRange($('#discovery'));
function renderDiscovery(){let output=$('#discoveryValue');if(output)output.textContent=`${state.discovery}%`;$('#discoverText').textContent=state.discovery<35?'В основном музыка, похожая на любимую':state.discovery>65?'Больше незнакомых исполнителей':'Поровну знакомого и новых открытий'}
$('#discovery').oninput=e=>{state.discovery=+e.target.value;WaveRecommendation.updateWavePreferences(waveSession,{noveltyLevel:state.discovery/100});renderDiscovery();save();invalidateNextBuffer('discovery')};renderDiscovery();
$('#discovery').onchange=()=>toast('Баланс обновлён — повлияет на следующий трек');
$('#crossfadeEnabled').checked=state.crossfadeEnabled;$('#crossfadeDuration').value=state.crossfadeDuration;
function renderCrossfadeSetting(){let enabled=$('#crossfadeEnabled').checked,duration=+$('#crossfadeDuration').value;$('#crossfadeValue').textContent=`${duration.toLocaleString('ru-RU')} сек`;$('.transition-setting').classList.toggle('disabled',!enabled)}
$('#crossfadeEnabled').onchange=e=>{state.crossfadeEnabled=e.target.checked;save();renderCrossfadeSetting()};
$('#crossfadeDuration').oninput=e=>{state.crossfadeDuration=+e.target.value;state.crossfadeEnabled=state.crossfadeDuration>0;$('#crossfadeEnabled').checked=state.crossfadeEnabled;save();renderCrossfadeSetting()};renderCrossfadeSetting();
function fallbackQueue(){let m=MOODS.find(x=>x[0]===state.mood)||MOODS[0];return Array.from({length:9},(_,i)=>({title:TITLES[(i+Math.floor(Math.random()*9))%9],artist:ARTISTS[Math.floor(Math.random()*7)],genre:state.genres[i%Math.max(1,state.genres.length)]||'Разное',mood:m[0],tempo:m[2]+(i%3-1)*5,color:m[3],duration:105+(i*13)%76,reason:'Локальный демо-режим',source:'Local Demo'}))}
const shuffle=a=>a.map(x=>[Math.random(),x]).sort((a,b)=>a[0]-b[0]).map(x=>x[1]);
const genreMap=Object.fromEntries(GENRE_PAIRS);
const moodMap={'Спокойствие':['peaceful','chill','cool','relaxing'],'Энергия':['energizing','fiery','excited','upbeat'],'Фокус':['focused','sophisticated','serious'],'Мечтательно':['dreamy','romantic','sentimental','yearning'],'Вечеринка':['party','excited','upbeat','energizing']};
function normalize(t,m){let source=t.source==='Local Demo'?'Local Demo':String(t.source||'audius').toLowerCase().replace('internet archive','archive'),track=WaveTrackModel.normalizeTrack(t,source);return {...track,color:t.color||m[3],duration:track.duration||180,genre:track.genre||'Разное',mood:track.mood||'',reason:t._reason||track.reason}}
function releaseLabel(value){if(!value)return '';let date=new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})}
const openAudius=t=>t.is_available!==false&&t.access?.stream!==false&&!t.stream_conditions&&!t.is_stream_gated&&!t.is_unlisted&&!t.is_delete&&!!t.track_cid;
async function fetchArchiveTracks(query){
  let q=encodeURIComponent(`mediatype:audio AND format:"VBR MP3" AND licenseurl:[* TO *] AND (${query||'music'})`),url=`https://archive.org/advancedsearch.php?q=${q}&fl[]=identifier&fl[]=title&fl[]=creator&fl[]=licenseurl&rows=8&output=json`;
  let search=await fetch(url,{signal:AbortSignal.timeout(9000)}).then(r=>r.json()),docs=search.response?.docs||[];
  let items=await Promise.all(docs.map(async doc=>{try{let meta=await fetch(`https://archive.org/metadata/${encodeURIComponent(doc.identifier)}`,{signal:AbortSignal.timeout(9000)}).then(r=>r.json());let file=(meta.files||[]).find(f=>['VBR MP3','MP3'].includes(f.format)&&f.name&&!f.name.includes('_64kb'));if(!file)return null;return{id:`ia:${doc.identifier}`,title:doc.title||file.title||doc.identifier,artist:Array.isArray(doc.creator)?doc.creator[0]:doc.creator||'Internet Archive',genre:query||'Открытая музыка',duration:Math.round(+file.length)||180,artwork:`https://archive.org/services/img/${encodeURIComponent(doc.identifier)}`,stream:`https://archive.org/download/${encodeURIComponent(doc.identifier)}/${file.name.split('/').map(encodeURIComponent).join('/')}`,source:'Internet Archive',_reason:'Открытая лицензия · Internet Archive'}}catch{return null}}));
  return items.filter(Boolean)
}
async function loadCatalog(force=false,merge=false,quiet=false){
  if(catalog.length&&!force&&Date.now()-catalogLoadedAt<15*60*1000)return catalog;
  let m=MOODS.find(x=>x[0]===state.mood)||MOODS[0];
  try{
    let genres=state.genres.slice(0,8).map(label=>genreMap[label]||label),source=await sourceManager.getCatalog({genres}),combined=sourceManager.deduplicate([...(merge?catalog:[]),...source].map(t=>normalize(t,m))),selection=WaveGenre.selectPool(combined,genres);
    if(selection.tracks.length<12){let queries=[...new Set(genres.flatMap(g=>WaveGenre.queriesFor(g)))].slice(0,6),settled=await Promise.allSettled(queries.map(q=>sourceManager.searchTracks(q)));settled.forEach(result=>{if(result.status==='fulfilled')combined.push(...result.value.map(t=>normalize(t,m)))});combined=sourceManager.deduplicate(combined);selection=WaveGenre.selectPool(combined,genres)}
    if(!selection.tracks.length)selection=WaveGenre.selectPool(combined,genres,{emergency:true});
    console.info('GENRE_FALLBACK',{selected:genres,level:selection.level,fallback:selection.fallback,candidates:selection.tracks.length,total:combined.length});
    catalog=sourceManager.deduplicate(selection.tracks);if(!catalog.length)throw Error('Каталог временно недоступен');catalogLoadedAt=Date.now();
  }catch(error){if(merge&&catalog.length)return catalog;catalog=fallbackQueue().map(t=>normalize(t,m));catalogLoadedAt=Date.now();if(!quiet)toast('Нет связи — включён локальный демо-режим')}
  return catalog;
}
function maybeReplenishCatalog(event,listenedSeconds){
  if(event==='error'||catalogRefreshInFlight)return;
  if(event==='ended'||listenedSeconds>=10)playedSinceCatalogRefresh++;
  let available=WaveRecommendation.eligibleCandidates(catalog,waveSession).candidates.length;
  if(playedSinceCatalogRefresh<12&&available>=15)return;
  playedSinceCatalogRefresh=0;catalogRefreshInFlight=true;void loadCatalog(true,true,true).finally(()=>{catalogRefreshInFlight=false});
}
function recommendationContext(){return {state,session:waveSession,selectedGenres:state.genres.map(label=>genreMap[label]||label),genreIntentStrength:state.genreIntentStrength}}
function chooseNextTrack(pool=catalog){
  let selected=WaveRecommendation.getNextTrack(pool,recommendationContext());if(!selected)return null;
  let t={...selected.track,reason:`${selected.selectionType} · настроение ${selected.moodScore.toFixed(2)} · новизна ${selected.userNoveltyScore.toFixed(2)}`};
  let debug={track_id:t.id,track_name:t.title,artist:t.artist,preference_score:+selected.preferenceScore.toFixed(4),preference_weight:selected.preferenceWeight,similarity_score:+selected.similarityScore.toFixed(4),similarity_weight:selected.similarityWeight,mood_score:+selected.moodScore.toFixed(4),mood_weight:selected.moodWeight,user_novelty_score:+selected.userNoveltyScore.toFixed(4),user_novelty_weight:selected.userNoveltyWeight,release_novelty_score:+selected.releaseNoveltyScore.toFixed(4),release_novelty_weight:selected.releaseNoveltyWeight,diversity_score:+selected.diversityScore.toFixed(4),diversity_weight:selected.diversityWeight,final_score:+selected.finalScore.toFixed(4),repeat_penalty:+selected.repeatPenalty.toFixed(4),artist_repeat_penalty:+selected.artistRepeatPenalty.toFixed(4),current_mood:waveSession.currentMood,novelty_level:waveSession.noveltyLevel,selection_type:selected.selectionType};
  window.__lastSelectionDebug=debug;console.table(debug);return t;
}
async function resolveAudiusStream(trackId){
  let response=await fetch(`https://api.audius.co/v1/tracks/${encodeURIComponent(trackId)}/stream?no_redirect=true`,{cache:'no-store',signal:AbortSignal.timeout(8000)});
  if(!response.ok)throw Error(`resolve HTTP ${response.status}`);
  let json=await response.json(),url=json?.data;
  if(typeof url!=='string'||!/^https:\/\//i.test(url))throw Error('Audius did not return a stream URL');
  return url;
}
async function probeStreamWithAudio(url){
  return new Promise((resolve,reject)=>{let probe=new Audio(),done=false,timer=setTimeout(()=>finish(false,Error('audio probe timeout')),8000),finish=(ok,value)=>{if(done)return;done=true;clearTimeout(timer);probe.pause();probe.removeAttribute('src');probe.load();ok?resolve(value):reject(value)};probe.muted=true;probe.preload='metadata';probe.onloadedmetadata=()=>finish(true,{status:0,contentType:'audio/browser-probe',validation:'audio-probe'});probe.oncanplay=()=>finish(true,{status:0,contentType:'audio/browser-probe',validation:'audio-probe'});probe.onerror=()=>finish(false,Error(`media ${probe.error?.code||0}: ${probe.error?.message||'stream error'}`));probe.src=url;probe.load()})
}
async function validateStreamUrl(url){
  try{
    let response=await fetch(url,{headers:{Range:'bytes=0-2047'},cache:'no-store',signal:AbortSignal.timeout(8000)}),contentType=(response.headers.get('content-type')||'').toLowerCase(),result={status:response.status,contentType,validation:'range-get'};
    if(response.body)void response.body.cancel();
    if(![200,206].includes(response.status)||!contentType.startsWith('audio/'))throw Object.assign(Error(`stream HTTP ${response.status}, type ${contentType||'missing'}`),{httpResult:result});
    return result;
  }catch(error){if(error?.httpResult)throw error;return probeStreamWithAudio(url)}
}
async function validateAudiusStream(track,rank,score){
  let id=WaveRecommendation.idOf(track),url;
  try{url=await resolveAudiusStream(id)}catch(error){console.warn('STREAM_RESOLVE_FAILED',{trackId:id,title:track.title,rank,error:error.message});failedTrackIds.add(id);return null}
  try{let result=await validateStreamUrl(url);console.log('STREAM_VALIDATE_OK',{trackId:id,status:result.status,contentType:result.contentType,source:track.source,validation:result.validation});verifiedPlayableTrackIds.set(id,Date.now()+PLAYABLE_CACHE_TTL);return {...track,stream:url}}
  catch(error){console.warn('STREAM_VALIDATE_FAILED',{trackId:id,title:track.title,rank,status:error?.httpResult?.status||0,error:error.message});failedTrackIds.add(id);return null}
}
async function validateCandidate(selected,rank){
  let track=selected.track,id=WaveRecommendation.idOf(track),cached=(verifiedPlayableTrackIds.get(id)||0)>Date.now();
  console.log('STREAM_VALIDATE_START',{trackId:id,title:track.title,rank,score:+selected.finalScore.toFixed(4)});
  if(track.source==='Local Demo')return track;
  try{let resolved=await sourceManager.resolveTrack(track);if(cached)return resolved;let result=await validateStreamUrl(resolved.stream);console.log('STREAM_VALIDATE_OK',{trackId:id,status:result.status,contentType:result.contentType,source:resolved.activeSource,validation:result.validation});verifiedPlayableTrackIds.set(id,Date.now()+PLAYABLE_CACHE_TTL);return resolved}
  catch(error){console.warn('STREAM_VALIDATE_FAILED',{trackId:id,title:track.title,rank,status:error?.httpResult?.status||0,error:error.message});failedTrackIds.add(id);return null}
}
function selectedTrack(selected,track){
  let t={...track,reason:`${selected.selectionType} · настроение ${selected.moodScore.toFixed(2)} · новизна ${selected.userNoveltyScore.toFixed(2)}`};
  let debug={track_id:t.id,track_name:t.title,artist:t.artist,preference_score:+selected.preferenceScore.toFixed(4),preference_weight:selected.preferenceWeight,similarity_score:+selected.similarityScore.toFixed(4),similarity_weight:selected.similarityWeight,mood_score:+selected.moodScore.toFixed(4),mood_weight:selected.moodWeight,user_novelty_score:+selected.userNoveltyScore.toFixed(4),user_novelty_weight:selected.userNoveltyWeight,release_novelty_score:+selected.releaseNoveltyScore.toFixed(4),release_novelty_weight:selected.releaseNoveltyWeight,diversity_score:+selected.diversityScore.toFixed(4),diversity_weight:selected.diversityWeight,final_score:+selected.finalScore.toFixed(4),repeat_penalty:+selected.repeatPenalty.toFixed(4),artist_repeat_penalty:+selected.artistRepeatPenalty.toFixed(4),current_mood:waveSession.currentMood,novelty_level:waveSession.noveltyLevel,selection_type:selected.selectionType};
  let chosenId=WaveRecommendation.idOf(t),selectionLog={chosenId,chosenTitle:t.title,recentTrackIds:waveSession.previousTracks.slice(-WAVE_RECOMMENDATION_CONFIG.hardTrackBlock).map(x=>String(x.id)),hardBlockedCount:selected.hardBlockedCount,eligibleCandidateCount:selected.eligibleCandidateCount,candidatePoolSize:selected.candidatePoolSize,rankBeforeSampling:selected.rankBeforeSampling,sampledPosition:selected.sampledPosition,finalScore:+selected.finalScore.toFixed(4),selectionType:selected.selectionType};
  window.__lastWaveSelections=[...window.__lastWaveSelections,chosenId].slice(-30);window.__lastWaveSelectionDebug=selectionLog;window.__lastSelectionDebug=debug;console.table(debug);console.log('WAVE_SELECTION',selectionLog);return t;
}
async function choosePlayableTrack(reservedIds=new Set()){
  let candidates=catalog.filter(t=>!failedTrackIds.has(WaveRecommendation.idOf(t))&&!reservedIds.has(WaveRecommendation.idOf(t))&&(sourceManager.sources.has(t.source)||!!t.stream||t.source==='Local Demo'));
  let context=recommendationContext(),eligible=WaveRecommendation.eligibleCandidates(candidates,waveSession),ranked=WaveRecommendation.getRankedCandidates(eligible.candidates,context,WAVE_RECOMMENDATION_CONFIG.candidateTopK),weighted=WaveRecommendation.getWeightedCandidateOrder(candidates,context,WAVE_RECOMMENDATION_CONFIG.candidateTopK),local=weighted.find(x=>x.track.source==='Local Demo'),ordered=weighted.filter(x=>x.track.source!=='Local Demo').slice(0,MAX_STREAM_VALIDATION_CANDIDATES);if(local)ordered.push(local);
  window.__lastCandidateRanking=ranked.slice(0,10).map((x,i)=>({rank:i+1,trackId:WaveRecommendation.idOf(x.track),title:x.track.title,score:+x.finalScore.toFixed(4),source:x.track.source}));
  window.__lastStreamValidation=[];
  for(let i=0;i<ordered.length;i++){let selected=ordered[i],playable=await validateCandidate(selected,i+1);window.__lastStreamValidation.push({rank:i+1,trackId:WaveRecommendation.idOf(selected.track),title:selected.track.title,score:+selected.finalScore.toFixed(4),source:selected.track.source,playable:!!playable});if(playable)return selectedTrack(selected,playable)}
  return null;
}
window.waveDebugSummary=()=>{let tracks=window.__lastWaveSelections.slice(-30),positions=new Map(),repeatingIds=new Set(),minimumRepeatDistance=null;tracks.forEach((id,index)=>{if(positions.has(id)){repeatingIds.add(id);let distance=index-positions.get(id);minimumRepeatDistance=minimumRepeatDistance===null?distance:Math.min(minimumRepeatDistance,distance)}positions.set(id,index)});let eligible=WaveRecommendation.eligibleCandidates(catalog.filter(t=>!failedTrackIds.has(WaveRecommendation.idOf(t))),waveSession);return {lastTracks:tracks,uniqueCount:new Set(tracks).size,repeatingIds:[...repeatingIds],minimumRepeatDistance,catalogSize:catalog.length,eligiblePoolSize:eligible.candidates.length,hardBlockWindow:eligible.windowSize}};
const current=()=>queue[index], fmt=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
function setPlayerState(nextState){if(playerState===nextState)return;playerState=nextState;let button=$('#play'),icon=button.querySelector('.control-icon'),orb=$('#waveOrb'),orbIcon=orb.querySelector('.orb-core i'),orbHint=orb.querySelector('.orb-core small'),playingNow=nextState===PLAYER_STATES.PLAYING,loading=nextState===PLAYER_STATES.LOADING,error=nextState===PLAYER_STATES.ERROR;button.dataset.state=nextState;icon.textContent=playingNow?'Ⅱ':error?'!':'▶';button.setAttribute('aria-label',playingNow?'Пауза':error?'Повторить воспроизведение':loading?'Загрузка':'Воспроизвести');document.querySelectorAll('[data-player-action="play"]').forEach(control=>{control.dataset.state=nextState;control.setAttribute('aria-label',playingNow?'Пауза':loading?'Загрузка':'Воспроизвести')});document.querySelectorAll('[data-play-icon] use').forEach(use=>use.setAttribute('href',playingNow?'#i-pause':'#i-play'));orb.dataset.state=nextState;orbIcon.textContent=playingNow?'Ⅱ':error?'↻':loading?'':'▶';orbHint.textContent=playingNow?'сейчас играет':nextState===PLAYER_STATES.PAUSED?'на паузе':loading?'подбираем музыку':error?'нажми, чтобы повторить':'нажми, чтобы включить';orb.setAttribute('aria-label',playingNow?'Поставить мою волну на паузу':error?'Повторить запуск моей волны':loading?'Моя волна загружается':'Запустить мою волну');orb.classList.remove('icon-swap');void orb.offsetWidth;orb.classList.add('icon-swap');document.body.classList.toggle('wave-playing',playingNow);console.log('PLAYER_STATE',nextState);console.log('PLAYER_BUTTON_STATE',{state:nextState,icon:orbIcon.textContent,hint:orbHint.textContent})}
function cancelPreloadAudio(){if(!preloadMedia)return;preloadMedia.oncanplay=null;preloadMedia.onloadedmetadata=null;preloadMedia.onerror=null;preloadMedia.pause();preloadMedia.removeAttribute('src');preloadMedia.load();preloadMedia=null;preloadReady=false}
function invalidateNextBuffer(reason='manual'){preloadRequestId++;playbackBuffer.next=null;playbackBuffer.backupNext=null;cancelPreloadAudio();console.log('PRELOAD_INVALIDATED',{reason,requestId:preloadRequestId});if(current()&&reason!=='start')void fillPlaybackBuffer()}
function preloadTrack(track,requestId){cancelPreloadAudio();if(!track?.stream)return;let element=new Audio(),isIOS=/iP(?:hone|ad|od)/.test(navigator.userAgent);preloadMedia=element;preloadReady=false;element.dataset.trackId=String(track.id);element.preload=isIOS?'metadata':'auto';element.volume=+$('#volume').value/100;console.log('PRELOAD_START',{trackId:track.id,title:track.title,source:track.activeSource||track.source,bufferPosition:'next'});let ready=()=>{if(requestId!==preloadRequestId||preloadMedia!==element)return;preloadReady=true;console.log('PRELOAD_READY',{trackId:track.id,title:track.title,source:track.activeSource||track.source,readyState:element.readyState,bufferPosition:'next'})};element.oncanplay=ready;element.onloadedmetadata=()=>{if(isIOS)ready()};element.onerror=()=>{if(requestId!==preloadRequestId)return;console.warn('PRELOAD_FAILED',{trackId:track.id,title:track.title,source:track.activeSource||track.source});preloadReady=false};element.src=track.stream;element.load()}
async function fillPlaybackBuffer(){if(bufferFillPromise)return bufferFillPromise;let requestId=++preloadRequestId;bufferFillPromise=(async()=>{let reserved=new Set([current(),playbackBuffer.next,playbackBuffer.backupNext].filter(Boolean).map(WaveRecommendation.idOf));try{if(!playbackBuffer.next){console.log('PRELOAD_SELECT',{bufferPosition:'next',requestId});let nextTrack=await choosePlayableTrack(reserved);if(requestId!==preloadRequestId)return;if(nextTrack){playbackBuffer.next=nextTrack;reserved.add(WaveRecommendation.idOf(nextTrack));preloadTrack(nextTrack,requestId)}}else if(!preloadMedia)preloadTrack(playbackBuffer.next,requestId);if(!playbackBuffer.backupNext){console.log('PRELOAD_SELECT',{bufferPosition:'backupNext',requestId});let backup=await choosePlayableTrack(reserved);if(requestId!==preloadRequestId)return;if(backup)playbackBuffer.backupNext=backup}}finally{bufferFillPromise=null;if(requestId!==preloadRequestId&&current())queueMicrotask(()=>fillPlaybackBuffer())}})();return bufferFillPromise}
window.wavePlayerDebug=()=>({current:current(),next:playbackBuffer.next,backup:playbackBuffer.backupNext,currentSource:current()?.activeSource||current()?.source,playerState,audioReadyState:media?.readyState??null,audioNetworkState:media?.networkState??null,preloadReadyState:preloadMedia?.readyState??null,preloadReady,sources:sourceManager.debug()});
window.waveGenreDebug=track=>{let t=track||current(),selected=state.genres.map(label=>genreMap[label]||label),best=t&&selected.length?selected.map(label=>({label,...WaveGenre.match(t,label)})).sort((a,b)=>b.score-a.score)[0]:null;return t?{title:t.title,artist:t.artist,source:t.source,selectedGenre:selected,rawGenre:t.rawGenre,normalizedGenre:t.normalizedGenre,subgenres:t.subgenres,genreConfidence:t.genreConfidence,language:t.language,languageConfidence:t.languageConfidence,match:best}:null};
window.waveMoodDebug=track=>{let t=track||current();if(!t)return null;let result=WaveMood.score(t,state.mood,state);return {...window.waveGenreDebug(t),mood:state.mood,moodDirection:result.direction,moodScore:result.score,moodConfidence:result.confidence,moodReasons:result.reasons,bpm:t.bpm,energy:t.energy,valence:t.valence,danceability:t.danceability}};
window.waveMoodSessionDebug=()=>({selectedMood:state.mood,selectedGenre:state.genres.map(label=>genreMap[label]||label),genreIntentStrength:state.genreIntentStrength,currentMoodDirection:current()?WaveMood.directionOf(current(),state.mood):null,genreAffinities:state.moodIntent?.[state.mood]?.genres||{},subgenreAffinities:state.moodIntent?.[state.mood]?.subgenres||{},directionAffinities:state.moodIntent?.[state.mood]?.directions||{},skipStreak:state.moodSkipStreak||null,explorationLevel:state.moodSkipStreak?.explorationLevel||0,recentlySuppressedDirections:state.moodSkipStreak?.suppressedDirections||[],last10:(state.moodIntent?.[state.mood]?.signals||[]).slice(0,10),directionProfile:WaveMood.directions[state.mood]});
function crossfadeSeconds(event){if(!state.crossfadeEnabled||state.crossfadeDuration<=0)return 0;if(event==='dislike'||event==='skip')return .5;if(event==='next'||event==='error')return Math.min(state.crossfadeDuration,2);return state.crossfadeDuration}
function animateCrossfade(oldMedia,newMedia,seconds,targetVolume){return new Promise(resolve=>{let duration=Math.max(0,seconds*1000),started=performance.now(),lastProgress=-1;cancelAnimationFrame(crossfadeFrame);console.log('CROSSFADE_START',{duration:seconds,from:oldMedia?.dataset.trackId,to:newMedia?.dataset.trackId});let step=now=>{let ratio=duration?Math.min(1,(now-started)/duration):1,eased=ratio*ratio*(3-2*ratio);if(oldMedia)oldMedia.volume=Math.max(0,targetVolume*(1-eased));if(newMedia)newMedia.volume=Math.min(1,targetVolume*eased);let quarter=Math.floor(ratio*4);if(quarter!==lastProgress){lastProgress=quarter;console.log('CROSSFADE_PROGRESS',{progress:+ratio.toFixed(2),currentVolume:oldMedia?.volume??0,nextVolume:newMedia?.volume??0})}if(ratio<1){crossfadeFrame=requestAnimationFrame(step);return}if(oldMedia){oldMedia.pause();try{oldMedia.currentTime=0}catch{}oldMedia.removeAttribute('src');oldMedia.load()}console.log('CROSSFADE_END',{duration:seconds});resolve()};crossfadeFrame=requestAnimationFrame(step)})}
function commitNextTrack(chosen){queue=queue.slice(0,index+1);queue.push(chosen);index=queue.length-1;load()}
async function crossfadeTo(chosen,event){let oldMedia=media,newMedia=preloadMedia,seconds=crossfadeSeconds(event),target=+$('#volume').value/100;if(!oldMedia||!newMedia||!preloadReady||newMedia.dataset.trackId!==String(chosen.id)||seconds<=0)return false;crossfadeInProgress=true;oldMedia.onended=null;oldMedia.onerror=null;oldMedia.onpause=null;newMedia.dataset.crossfadeStart='true';playbackBuffer.next=playbackBuffer.backupNext;playbackBuffer.backupNext=null;commitNextTrack(chosen);playing=true;sound(chosen);await animateCrossfade(oldMedia,newMedia,seconds,target);delete media.dataset.crossfadeStart;crossfadeInProgress=false;return true}
window.waveCrossfadeDebug=()=>({current:current(),next:playbackBuffer.next,crossfadeEnabled:state.crossfadeEnabled,duration:state.crossfadeDuration,currentVolume:media?.volume??null,nextVolume:preloadMedia?.volume??null,playerState,crossfadeInProgress});
function unlockPlayback(){
  if(media)return;
  media=new Audio('data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=');
  media.dataset.unlock='true';media.volume=0;media.play().catch(()=>{});
}
async function start(){if(selectionInProgress)return;selectionInProgress=true;unlockPlayback();invalidateNextBuffer('start');failedTrackIds.clear();verifiedPlayableTrackIds.clear();playbackRetryCount=0;playbackStoppedOnError=false;setPlayerState(PLAYER_STATES.LOADING);$('#waveOrb').disabled=true;$('#player').classList.add('visible');$('#miniPlayer').classList.add('visible');document.querySelectorAll('[data-player-title]').forEach(x=>x.textContent='Подбираем доступный трек…');document.querySelectorAll('[data-player-artist]').forEach(x=>x.textContent='Проверяем источники аудио');try{await loadCatalog(true);let first=await choosePlayableTrack();if(!first){setPlayerState(PLAYER_STATES.ERROR);return toast('Не удалось подобрать трек с доступным аудио')}queue=[first];index=0;load();void play()}finally{selectionInProgress=false;$('#waveOrb').disabled=false}}
function renderPlayerUI(){let t=current();if(!t)return;let details=`${t.artist} · ${t.genre} · ${t.reason}`,background=t.artwork?`center/cover url("${t.artwork}")`:`linear-gradient(135deg,${t.color||'#8052ff'},#17131e)`;document.querySelectorAll('[data-player-title]').forEach(x=>x.textContent=t.title);document.querySelectorAll('[data-player-artist]').forEach(x=>x.textContent=details);document.querySelectorAll('[data-player-source]').forEach(x=>x.textContent=t.activeSource||t.source||'');document.querySelectorAll('[data-player-artwork]').forEach(x=>x.style.background=background);$('#duration').textContent=fmt(t.duration);$('#mobileDuration').textContent=fmt(t.duration);$('#player').classList.add('visible');$('#miniPlayer').classList.add('visible');likeVisual();renderRepeat();renderQueue()}
function updateProgressUI(seconds=elapsed){let t=current();if(!t)return;let ratio=Math.max(0,Math.min(100,seconds/t.duration*100));$('#time').textContent=fmt(Math.floor(seconds));$('#mobileTime').textContent=fmt(Math.floor(seconds));for(let input of [$('#progress'),$('#mobileProgress')]){input.value=ratio;paintRange(input)}document.querySelectorAll('[data-player-progress]').forEach(x=>x.style.setProperty('--progress',`${ratio}%`))}
function load(){let t=current();if(!t)return;elapsed=0;waveSession.currentTrackId=WaveRecommendation.idOf(t);if(!waveSession.seedTrackId)waveSession.seedTrackId=waveSession.currentTrackId;playbackBuffer.current=t;renderPlayerUI();updateProgressUI(0);updateMediaSession(t);save()}
function updateMediaSession(t){
  document.title=`${t.title} — ${t.artist} | Волна`;
  if(!('mediaSession'in navigator))return;
  navigator.mediaSession.metadata=new MediaMetadata({title:t.title,artist:t.artist,album:`Волна · ${t.genre}`,artwork:t.artwork?[{src:t.artwork,sizes:'480x480'}]:[{src:'wave-icon.svg',sizes:'512x512',type:'image/svg+xml'}]});
}
function seekTo(seconds){if(!current())return;elapsed=Math.max(0,Math.min(seconds,current().duration-1));if(media&&media.readyState>0)media.currentTime=elapsed;updateProgressUI(elapsed)}
function handleTrackEnded(){if(state.repeatCurrent&&current()){recordPlayback('ended');elapsed=0;updateProgressUI(0);if(media){media.currentTime=0;void media.play().catch(handlePlayRejection)}else{stopSound();sound(current())}return}void next('ended')}
async function play(){if(!current())return start();if(playbackStoppedOnError){playbackStoppedOnError=false;return next('error',true)}tabChannel?.postMessage('claim-audio');playing=true;setPlayerState(PLAYER_STATES.LOADING);if('mediaSession'in navigator)navigator.mediaSession.playbackState='playing';sound(current());clearInterval(timer);timer=setInterval(()=>{elapsed=media?Math.floor(media.currentTime):elapsed+1;let autoFade=state.repeatCurrent?0:crossfadeSeconds('ended');if(!crossfadeInProgress&&autoFade>0&&preloadReady&&playbackBuffer.next&&current().duration-elapsed<=autoFade)return void next('ended');if(elapsed>=current().duration)return handleTrackEnded();updateProgressUI(elapsed)},500);void fillPlaybackBuffer()}
function pause(){playing=false;setPlayerState(current()?PLAYER_STATES.PAUSED:PLAYER_STATES.IDLE);if('mediaSession'in navigator)navigator.mediaSession.playbackState='paused';clearInterval(timer);if(media)media.pause();else stopSound()}
function progressRatio(){let duration=Number(current()?.duration)||1,position=media&&Number.isFinite(media.currentTime)?media.currentTime:elapsed;return Math.max(0,Math.min(1,position/duration))}
function recordPlayback(event){let ratio=event==='ended'?1:progressRatio(),listenedSeconds=event==='ended'?Number(current()?.duration)||elapsed:media&&Number.isFinite(media.currentTime)?media.currentTime:elapsed;WaveRecommendation.recordEvent(state,waveSession,current(),event,{progressRatio:ratio,listenedSeconds});maybeReplenishCatalog(event,listenedSeconds);save();libraries()}
async function next(event='next',alreadyRecorded=false){if(!current())return start();if(selectionInProgress||crossfadeInProgress)return;selectionInProgress=true;nextStartedAt=performance.now();let resume=playing;if(!alreadyRecorded)recordPlayback(event);let chosen=playbackBuffer.next;if(chosen)console.log('PRELOAD_SWAP',{trackId:chosen.id,title:chosen.title,ready:preloadReady});else{setPlayerState(PLAYER_STATES.LOADING);$('#title').textContent='Подбираем доступный трек…';$('#artist').textContent='Проверяем источники аудио';try{chosen=await choosePlayableTrack()}catch{}}if(!chosen){selectionInProgress=false;setPlayerState(PLAYER_STATES.ERROR);return toast('Не удалось подобрать следующий трек с доступным аудио')}if(event!=='error')playbackRetryCount=0;playbackStoppedOnError=false;let faded=false;try{faded=await crossfadeTo(chosen,event)}catch(error){console.warn('CROSSFADE_FALLBACK',{error:error.message})}if(!faded){console.log('CROSSFADE_FALLBACK',{reason:crossfadeSeconds(event)<=0?'disabled':preloadReady?'unavailable':'preload-not-ready'});let old=media,fadeSeconds=Math.min(crossfadeSeconds(event),.5);if(old&&fadeSeconds>0)await animateCrossfade(old,null,fadeSeconds,+$('#volume').value/100);else if(old&&preloadMedia!==old)old.pause();if(playbackBuffer.next===chosen){playbackBuffer.next=playbackBuffer.backupNext;playbackBuffer.backupNext=null}commitNextTrack(chosen);if(resume||['next','ended','skip','dislike','error'].includes(event))void play()}selectionInProgress=false;void fillPlaybackBuffer()}
function prev(){pause();index=(index-1+queue.length)%queue.length;load();play()}
function handlePlayRejection(error){if(error?.name==='NotAllowedError')return showPlayRequired();if(error?.name==='AbortError')return;setTimeout(()=>{if(!media?.error){playing=false;setPlayerState(PLAYER_STATES.ERROR);clearInterval(timer);console.warn('PLAYBACK_START_REJECTED',{name:error?.name,message:error?.message});$('#artist').textContent='Не удалось запустить аудио. Нажми ▶, чтобы повторить.'}},0)}
async function trySameTrackFallback(track){let alternative=(track.alternatives||[]).find(x=>x.source!==track.activeSource);if(!alternative)return false;try{let resolved=await sourceManager.resolveTrack({...alternative,alternatives:[]}),replacement={...track,stream:resolved.stream,streamUrl:resolved.streamUrl,activeSource:resolved.activeSource,alternatives:(track.alternatives||[]).filter(x=>x.source!==resolved.activeSource)};queue[index]=replacement;playbackBuffer.current=replacement;console.log('SOURCE_FALLBACK',{trackId:track.id,from:track.activeSource||track.source,to:replacement.activeSource});sound(replacement);return true}catch(error){console.warn('SOURCE_FALLBACK_FAILED',{trackId:track.id,source:alternative.source,error:error.message});return false}}
function sound(t){
  if(t.stream){
    let prepared=preloadMedia?.dataset.trackId===String(t.id);if(prepared){if(media&&media!==preloadMedia&&!preloadMedia.dataset.crossfadeStart){media.pause();media.onended=null;media.onerror=null}media=preloadMedia;preloadMedia=null;preloadReady=false}else if(media?.dataset.trackId!==String(t.id)){let unlocked=media?.dataset.unlock==='true';if(!unlocked){stopSound();media=new Audio()}else{media.pause();media.removeAttribute('src')}}delete media.dataset.unlock;media.dataset.trackId=String(t.id);media.preload='auto';media.volume=media.dataset.crossfadeStart?0:+$('#volume').value/100;media.onended=handleTrackEnded;
    let originalMeta=$('#artist').textContent,loadTimer=setTimeout(()=>{$('#artist').textContent='Загружаем аудио… обычно 2–5 секунд'},700);
    media.onloadedmetadata=()=>{if(elapsed>0&&elapsed<media.duration)media.currentTime=elapsed};
    media.onplay=()=>setPlayerState(PLAYER_STATES.LOADING);media.onwaiting=media.onstalled=()=>setPlayerState(PLAYER_STATES.LOADING);media.onpause=()=>{if(!media.ended&&playerState!==PLAYER_STATES.LOADING)setPlayerState(PLAYER_STATES.PAUSED)};media.oncanplay=()=>{clearTimeout(loadTimer);$('#artist').textContent=originalMeta};media.onplaying=()=>{setPlayerState(PLAYER_STATES.PLAYING);playbackRetryCount=0;playbackStoppedOnError=false;if(nextStartedAt){console.log('NEXT_LATENCY_MS',Math.round(performance.now()-nextStartedAt));nextStartedAt=0}};
    media.onerror=()=>{clearTimeout(loadTimer);let failed=current(),error=media?.error,wasPlaying=playing;console.warn('PLAYBACK_FAILED',{trackId:failed?.id,title:failed?.title,artist:failed?.artist,stream:failed?.stream,mediaErrorCode:error?.code||0,mediaErrorMessage:error?.message||'',networkState:media?.networkState,readyState:media?.readyState});setPlayerState(PLAYER_STATES.LOADING);void trySameTrackFallback(failed).then(recovered=>{if(recovered)return;failedTrackIds.add(WaveRecommendation.idOf(failed));playing=false;setPlayerState(PLAYER_STATES.ERROR);clearInterval(timer);if(wasPlaying&&playbackRetryCount<MAX_PLAYBACK_RETRIES){playbackRetryCount++;console.log('PLAYBACK_RETRY',{attempt:playbackRetryCount,maxAttempts:MAX_PLAYBACK_RETRIES});toast(`Поток недоступен — попытка ${playbackRetryCount} из ${MAX_PLAYBACK_RETRIES}`);setTimeout(()=>next('error',true),500)}else{playbackStoppedOnError=true;$('#artist').textContent='Не удалось получить аудио от источника. Нажми ▶, чтобы попробовать другой трек.';toast('Источник аудио недоступен — автоматические попытки остановлены')}})};
    if(!prepared&&media.src!==t.stream)media.src=t.stream;media.play().catch(error=>{clearTimeout(loadTimer);handlePlayRejection(error)});return
  }
  let AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio=new AC();let master=audio.createGain();master.gain.value=(+$('#volume').value/100)*.08;master.connect(audio.destination);let root=['Энергия','Вечеринка'].includes(t.mood)?146.83:110,notes=[1,1.25,1.5,2],step=0;let pulse=()=>{if(!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.type=t.genre==='Электроника'?'triangle':'sine';o.frequency.value=root*notes[step++%4];g.gain.setValueAtTime(.001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.35,audio.currentTime+.04);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.48);o.connect(g).connect(master);o.start();o.stop(audio.currentTime+.5)};pulse();audio.pulse=setInterval(pulse,60000/t.tempo)}
function showPlayRequired(){playing=false;setPlayerState(PLAYER_STATES.PAUSED);clearInterval(timer);$('#artist').textContent='Нажми ▶ для запуска звука';toast('Браузер ждёт нажатия кнопки ▶')}
function stopSound(preserveUnlock=false){if(media&&!(preserveUnlock&&media.dataset.unlock==='true')){media.onended=null;media.onerror=null;media.oncanplay=null;media.onplaying=null;media.pause();media.removeAttribute('src');media.load();media=null}if(audio){clearInterval(audio.pulse);audio.close();audio=null}}
function likeVisual(){let yes=current()&&state.likes.some(x=>WaveRecommendation.idOf(x)===WaveRecommendation.idOf(current()));let desktopIcon=$('#like .control-icon');if(desktopIcon)desktopIcon.textContent=yes?'♥':'♡';document.querySelectorAll('[data-player-action="like"]').forEach(button=>{button.classList.toggle('active',yes);button.setAttribute('aria-label',yes?'Убрать из любимых':'Добавить в любимые')})}
function renderRepeat(){document.querySelectorAll('[data-player-action="repeat"]').forEach(button=>{button.classList.toggle('active',state.repeatCurrent);button.setAttribute('aria-pressed',String(state.repeatCurrent))})}
function toggleRepeat(){state.repeatCurrent=!state.repeatCurrent;save();renderRepeat();toast(state.repeatCurrent?'Повтор текущего трека включён':'Повтор выключен')}
function renderQueue(){let box=$('#queueList');if(!box)return;let tracks=[current(),playbackBuffer.next,playbackBuffer.backupNext].filter(Boolean),labels=['Сейчас','Далее','После'];box.innerHTML=tracks.length?tracks.map((t,i)=>`<div class="queue-item ${i===0?'current':''}"><span>${labels[i]||i+1}</span><i class="queue-art" style="${t.artwork?`background-image:url('${escapeHtml(t.artwork)}')`:`background:${t.color||'#8052ff'}`}"></i><span><strong>${escapeHtml(t.title)}</strong><small>${escapeHtml(t.artist||'Исполнитель')}</small></span></div>`).join(''):'<div class="queue-empty">Запусти волну — здесь появятся следующие треки</div>'}
function toggleLike(){let t=current();if(!t)return;let yes=state.likes.some(x=>WaveRecommendation.idOf(x)===WaveRecommendation.idOf(t));WaveRecommendation.recordEvent(state,waveSession,t,yes?'unlike':'like',{progressRatio:progressRatio(),listenedSeconds:media?.currentTime||elapsed});save();libraries();likeVisual();toast(yes?'Убрано из любимых':'Вкус обновлён — следующий подбор учтёт лайк')}
function list(a,msg){return a.length?a.map(t=>`<div class="track"><i style="--color:${t.color}">♪</i><span><strong>${t.title}</strong><small>${t.artist} · ${t.genre}</small></span><time>${fmt(t.duration)}</time></div>`).join(''):`<div class="empty">${msg}</div>`}
function libraries(){$('#likesList').innerHTML=list(state.likes,'Пока пусто — нажми ♡ у понравившегося трека');$('#historyList').innerHTML=list(state.history,'История появится после запуска волны')}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function syncOverlayLock(){document.body.classList.toggle('overlay-open',document.querySelector('.full-player.open,.bottom-sheet.open')||document.body.classList.contains('search-sheet-open'))}
function showPage(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.desktop-nav [data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));if(page==='likes'||page==='history')libraries();window.scrollTo({top:0,behavior:'smooth'})}
function openSearch(){showPage('home');document.body.classList.add('search-sheet-open');syncOverlayLock();setTimeout(()=>$('#musicSearch').focus(),50)}
function closeSearch(){document.body.classList.remove('search-sheet-open');syncOverlayLock()}
function openFullPlayer(){if(!current())return toast('Сначала запусти волну');closeSearch();$('#fullPlayer').classList.add('open');$('#fullPlayer').setAttribute('aria-hidden','false');syncOverlayLock();setTimeout(()=>$('[data-close-player]').focus(),60)}
function closeFullPlayer(){closeSheets();$('#fullPlayer').classList.remove('open');$('#fullPlayer').style.transform='';$('#fullPlayer').setAttribute('aria-hidden','true');syncOverlayLock();document.querySelector('[data-open-player]')?.focus()}
function closeSheets(){document.querySelectorAll('.bottom-sheet,.sheet-backdrop').forEach(x=>x.classList.remove('open'));document.querySelectorAll('.bottom-sheet').forEach(x=>x.setAttribute('aria-hidden','true'));syncOverlayLock()}
function openSheet(sheet){closeSheets();sheet.classList.add('open');sheet.setAttribute('aria-hidden','false');$('.sheet-backdrop').classList.add('open');syncOverlayLock();setTimeout(()=>sheet.querySelector('button')?.focus(),40)}
function showQueue(){renderQueue();openSheet($('#queueSheet'));void fillPlaybackBuffer().then(renderQueue)}
async function shareCurrent(){let t=current();if(!t)return toast('Сначала запусти волну');let data={title:`${t.title} — ${t.artist}`,text:`Слушаю ${t.title} — ${t.artist} в «Волне»`,url:location.href};try{if(navigator.share)await navigator.share(data);else if(navigator.clipboard){await navigator.clipboard.writeText(`${data.text} ${data.url}`);toast('Ссылка скопирована')}else throw Error('share unavailable')}catch(error){if(error?.name!=='AbortError')toast('Не удалось поделиться')}}
function dislikeCurrent(){if(!current())return;recordPlayback('dislike');toast('Дизлайк учтён — выбираем другой трек');void next('dislike',true)}
function resetPreferences(){if(confirm('Сбросить выбранные жанры, настроение, лайки и историю?')){localStorage.removeItem('waveState');location.reload()}}
function runPlayerAction(action){if(action==='play')return playing?pause():play();if(action==='next')return void next('next');if(action==='prev')return prev();if(action==='like')return toggleLike();if(action==='dislike')return dislikeCurrent();if(action==='repeat')return toggleRepeat();if(action==='queue')return showQueue();if(action==='share')return void shareCurrent()}
$('#waveOrb').onclick=()=>playing?pause():current()?play():start();$('#reset').onclick=resetPreferences;document.querySelector('[data-reset-preferences]').onclick=resetPreferences;
document.addEventListener('click',event=>{let action=event.target.closest('[data-player-action]')?.dataset.playerAction;if(action){event.preventDefault();event.stopPropagation();runPlayerAction(action)}});
$('#volume').oninput=()=>{if(media)media.volume=+$('#volume').value/100;else if(playing){stopSound();sound(current())}};
for(let input of [$('#progress'),$('#mobileProgress')])input.oninput=e=>{if(current())seekTo(current().duration*e.target.value/100)};
document.querySelectorAll('.desktop-nav [data-page]').forEach(button=>button.onclick=()=>showPage(button.dataset.page));
document.querySelectorAll('.brand,.top-brand').forEach(link=>link.onclick=event=>{event.preventDefault();showPage('home')});
document.querySelector('[data-open-player]').onclick=openFullPlayer;document.querySelector('[data-close-player]').onclick=closeFullPlayer;document.querySelector('[data-close-search]').onclick=closeSearch;document.querySelectorAll('[data-close-sheet]').forEach(x=>x.onclick=closeSheets);
document.querySelector('[data-sheet-page]').onclick=()=>{closeSheets();showPage('history')};
document.querySelectorAll('[data-mobile-target]').forEach(button=>button.onclick=()=>{let target=button.dataset.mobileTarget;document.querySelectorAll('[data-mobile-target]').forEach(x=>x.classList.toggle('active',x===button));if(target==='search')return openSearch();if(target==='likes')return showPage('likes');if(target==='genres'){closeSearch();showPage('home');return setTimeout(()=>$('#genreSection').scrollIntoView({behavior:'smooth',block:'start'}),50)}if(target==='more')return openSheet($('#moreSheet'));closeSearch();showPage('home')});
let dragStart=null,dragY=0,dragHandle=$('.player-drag-handle');dragHandle.onpointerdown=event=>{dragStart={y:event.clientY,time:performance.now()};dragY=0;dragHandle.setPointerCapture(event.pointerId)};dragHandle.onpointermove=event=>{if(!dragStart)return;dragY=Math.max(0,event.clientY-dragStart.y);$('#fullPlayer').style.transform=`translateY(${dragY}px)`};dragHandle.onpointerup=event=>{if(!dragStart)return;let fast=dragY>35&&performance.now()-dragStart.time<260,close=dragY>85||fast;dragStart=null;dragHandle.releasePointerCapture(event.pointerId);if(close)closeFullPlayer();else $('#fullPlayer').style.transform=''};
document.addEventListener('keydown',event=>{let layer=document.querySelector('.bottom-sheet.open,.full-player.open');if(event.key==='Tab'&&layer){let focusable=[...layer.querySelectorAll('button:not([disabled]),input:not([disabled]),a[href]')].filter(x=>x.offsetParent!==null);if(focusable.length){let first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}return}if(event.key!=='Escape')return;if(document.querySelector('.bottom-sheet.open'))closeSheets();else if($('#fullPlayer').classList.contains('open'))closeFullPlayer();else closeSearch()});
window.addEventListener('scroll',()=>$('#scrollTop').classList.toggle('visible',scrollY>500),{passive:true});$('#scrollTop').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});setPlayerState(PLAYER_STATES.IDLE);renderRepeat();
if('mediaSession'in navigator){
  navigator.mediaSession.setActionHandler('play',()=>play());navigator.mediaSession.setActionHandler('pause',()=>pause());
  navigator.mediaSession.setActionHandler('previoustrack',()=>prev());navigator.mediaSession.setActionHandler('nexttrack',()=>next());
  navigator.mediaSession.setActionHandler('seekbackward',details=>seekTo(elapsed-(details.seekOffset||10)));
  navigator.mediaSession.setActionHandler('seekforward',details=>seekTo(elapsed+(details.seekOffset||10)));
  navigator.mediaSession.setActionHandler('seekto',details=>seekTo(details.seekTime||0));
}
if('serviceWorker'in navigator&&(location.protocol==='https:'||location.hostname==='localhost'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(tabChannel)tabChannel.onmessage=event=>{if(event.data==='claim-audio'&&playing){pause();toast('Музыка продолжилась в другой вкладке')}};
window.addEventListener('pageshow',event=>{if(event.persisted)location.reload()});
window.onbeforeunload=stopSound;choices();libraries();
