(async()=>{
await test('nested Audius stream objects normalize to distinct URLs',()=>{const manager=new WaveSourceManager([]),a=WaveTrackModel.normalizeTrack({...fixtureTrack(0),streamUrl:{url:'https://audio.test/a'}},'audius'),b=WaveTrackModel.normalizeTrack({...fixtureTrack(1),streamUrl:{url:'https://audio.test/b'}},'audius');return {pass:typeof a.streamUrl==='string'&&manager.deduplicate([a,b]).length===2}});

await test('each source and query advances its own page',async()=>{const calls=[],source={id:'audius',getTrendingTracks:async options=>{calls.push(['trending',options.offset]);return Array.from({length:options.limit},(_,i)=>({...fixtureTrack(i%60),id:'audius:trending'+(options.offset+i),sourceTrackId:'trending'+(options.offset+i),title:'Trending '+(options.offset+i)}))},getLatestTracks:async options=>{calls.push(['latest',options.offset]);return Array.from({length:options.limit},(_,i)=>({...fixtureTrack(i%60),id:'audius:latest'+(options.offset+i),sourceTrackId:'latest'+(options.offset+i),title:'Latest '+(options.offset+i)}))},getTracksByGenre:async(genre,options)=>{calls.push([genre,options.offset]);return Array.from({length:options.limit},(_,i)=>({...fixtureTrack(i%60),id:'audius:'+genre+(options.offset+i),sourceTrackId:genre+(options.offset+i),title:genre+(options.offset+i)}))}};const manager=new WaveSourceManager([source]);await manager.getCatalog({genres:['Pop']});await manager.getCatalog({genres:['Pop']});await manager.getCatalog({genres:['Rock']});return {pass:calls.some(x=>x[0]==='Pop'&&x[1]===40)&&calls.some(x=>x[0]==='Rock'&&x[1]===0)&&manager.catalogFetchCount===9,calls}});
await test('failed first eight take another bounded group',async()=>{let count=0;validateCandidate=async selected=>++count<=8?null:selected.track;const chosen=await choosePlayableTrack(new Set(),selectionToken(newPlaybackOperation('test')));releaseReservation(chosen?._reservationId);return {pass:!!chosen&&count>8&&count<=24,count}});
await test('all bad candidates stop within overall deadline and budget',async()=>{let count=0;validateCandidate=async()=>{count++;return null};await start();return {pass:count===24&&!selectionInProgress&&playerState==='ERROR',count,state:playerState}});
await test('temporary failures expire and hard failures cool down',()=>{const realNow=Date.now;let clock=realNow();Date.now=()=>clock;try{const failures=new WaveFailureCache();failures.add('temporary',{status:503});failures.add('missing',{httpResult:{status:404}});clock+=30001;const transientExpired=!failures.has('temporary'),hardRetained=failures.has('missing');failures.add('temporary',{name:'TimeoutError'});const backoff=failures.records.get('temporary').expiresAt-clock;clock+=60001;const retry=!failures.has('temporary');clock+=1800000;return {pass:transientExpired&&hardRetained&&backoff===60000&&retry&&!failures.has('missing'),transientExpired,hardRetained,backoff}}finally{Date.now=realNow}});
await test('dedupe IDs URLs aliases while preserving distinct metadata versions',()=>{const manager=new WaveSourceManager([]),base=fixtureTrack(0),alias={...base,id:'archive:copy',source:'archive',sourceTrackId:'copy'},sameUrl={...fixtureTrack(1),streamUrl:base.streamUrl},live={...alias,id:'archive:live',sourceTrackId:'live',streamUrl:'/fixture/live',title:base.title+' (Live)'},unknown1={...base,id:'archive:unknown1',sourceTrackId:'unknown1',title:'Unknown',duration:null,durationKnown:false,streamUrl:null},unknown2={...unknown1,id:'archive:unknown2',sourceTrackId:'unknown2'},tracks=manager.deduplicate([base,base,alias,sameUrl,live,unknown1,unknown2]);return {pass:tracks.length===4&&tracks.some(x=>x.title.endsWith('(Live)'))&&WaveRecommendation.isRecentlyPlayed({...alias},WaveRecommendation.createSession({previousTracks:[base]})),count:tracks.length}});
await test('catalog errors back off without advancing cursor',async()=>{let calls=0;const source={id:'archive',getTrendingTracks:async()=>{calls++;throw Error('transient')}};const manager=new WaveSourceManager([source]);await manager.getCatalog();await manager.getCatalog();const page=[...manager.catalogPages.values()][0];return {pass:calls===1&&page.offset===0&&page.retryAt>Date.now(),calls,page:{offset:page.offset,retryAt:page.retryAt}}});
await test('catalog fetch concurrency stays bounded',async()=>{let active=0,max=0;const method=async()=>{active++;max=Math.max(max,active);await Promise.resolve();active--;return []};const sources=['a','b','c'].map(id=>({id,getTrendingTracks:method,getLatestTracks:method,getTracksByGenre:method}));const manager=new WaveSourceManager(sources);await manager.getCatalog({genres:['Pop','Rock']});return {pass:max<=2&&active===0,max}});
window.controllerTestResults={results};document.body.dataset.failed=String(results.filter(x=>!x.pass).length);document.querySelector('#results').textContent=JSON.stringify(window.controllerTestResults,null,2);
})().catch(error=>{document.body.dataset.failed='1';document.querySelector('#results').textContent=error.stack});
