const results=[];function test(name,fn){return Promise.resolve().then(fn).then(()=>results.push(`PASS ${name}`),error=>results.push(`FAIL ${name}: ${error.message}`))}function assert(value,message){if(!value)throw Error(message)}
const track=(source,id,extra={})=>WaveTrackModel.normalizeTrack({id,title:'Numb (Official Audio)',artist:'Linkin Park',duration:185,...extra},source);
(async()=>{
  await test('one failed source does not break search',async()=>{let good={id:'good',searchTracks:async()=>[track('good','1')],getStream:async t=>({url:t.streamUrl})},bad={id:'bad',searchTracks:async()=>{throw Error('offline')},getStream:async()=>{throw Error('offline')}},manager=new WaveSourceManager([good,bad],{SOURCE_PRIORITY:['good','bad'],REQUEST_TIMEOUT_MS:30,METADATA_CACHE_TTL_MS:1});assert((await manager.searchTracks('numb')).length===1,'settled result missing')});
  await test('duplicate recordings merge and retain fallback',()=>{let manager=new WaveSourceManager([],{SOURCE_PRIORITY:['audius','archive']}),items=manager.deduplicate([track('archive','a'),track('audius','b')]);assert(items.length===1&&items[0].source==='audius'&&items[0].alternatives[0].source==='archive','dedupe or priority failed')});
  await test('real versions are not deduplicated',()=>{let manager=new WaveSourceManager([],{SOURCE_PRIORITY:[]}),items=manager.deduplicate([track('audius','a'),track('archive','b',{title:'Numb (Live)'})]);assert(items.length===2,'live version was removed')});
  await test('fallback source resolves same recording',async()=>{let a={id:'audius',getStream:async()=>{throw Error('down')}},b={id:'archive',getStream:async()=>({url:'https://audio.test/fallback.mp3'})},manager=new WaveSourceManager([a,b],{SOURCE_PRIORITY:['audius','archive'],REQUEST_TIMEOUT_MS:30}),primary=track('audius','1');primary.alternatives=[track('archive','2')];let resolved=await manager.resolveTrack(primary);assert(resolved.activeSource==='archive'&&resolved.stream.includes('fallback'),'fallback failed')});
  await test('timeout source does not block others',async()=>{let slow={id:'slow',searchTracks:(_q,{signal})=>new Promise((resolve,reject)=>{signal.addEventListener('abort',()=>reject(Error('timeout')))} )},fast={id:'fast',searchTracks:async()=>[track('fast','1')]},manager=new WaveSourceManager([slow,fast],{SOURCE_PRIORITY:['fast'],REQUEST_TIMEOUT_MS:20,METADATA_CACHE_TTL_MS:1}),started=performance.now(),found=await manager.searchTracks('x');assert(found.length===1&&performance.now()-started<200,'timeout blocked aggregate')});
  let failed=results.filter(x=>x.startsWith('FAIL')).length;document.querySelector('#results').textContent=`${failed?'FAILED':'PASSED'}\n${results.join('\n')}`;document.body.dataset.failed=String(failed)
})();
