const results=[];function test(name,fn){try{fn();results.push(`PASS ${name}`)}catch(error){results.push(`FAIL ${name}: ${error.message}`)}}function assert(value,message){if(!value)throw Error(message)}let request=new XMLHttpRequest();request.open('GET','../app.js',false);request.send();const source=request.responseText;
test('buffer is current next backup only',()=>assert(source.includes('playbackBuffer={current:null,next:null,backupNext:null}')&&!source.includes('buildQueue('),'small buffer missing'));
test('preload does not record history',()=>{let body=source.match(/function preloadTrack\([\s\S]*?\n}/)?.[0]||'';assert(body&&!body.includes('recordPlayback')&&!body.includes('recordEvent'),'preload records listening')});
test('preload invalidation uses request id',()=>assert(source.includes('preloadRequestId++')&&source.includes("invalidateNextBuffer('mood')")&&source.includes("invalidateNextBuffer('discovery',true)")&&source.includes("invalidateNextBuffer('genre')"),'stale preload guard missing'));
test('reserved ids protect anti-repeat',()=>assert(source.includes('reservedIds.has(WaveRecommendation.idOf(t))'),'reserved buffer tracks are eligible'));
test('media events drive player state',()=>['onplay','onplaying','onpause','onwaiting','onstalled','oncanplay','onended','onerror'].forEach(event=>assert(source.includes(event),`${event} missing`)));
test('ready next path reports latency',()=>assert(source.includes("logPlayback('NEXT_LATENCY'")&&source.includes('latencyMs:Math.round(performance.now()-nextStartedAt)'),'swap metrics missing'));
test('failed next has backup',()=>assert(source.includes('playbackBuffer.backupNext')&&source.includes("next('error',true)"),'backup error path missing'));
test('wave button resumes instead of rebuilding wave',()=>assert(source.includes("current()?play():start()"),'paused wave button restarts selection'));
test('button states are media-event driven',()=>['IDLE','LOADING','PLAYING','PAUSED','ERROR','PLAYER_BUTTON_STATE'].forEach(value=>assert(source.includes(value),`${value} missing`)));
test('crossfade setting persists in wave state',()=>assert(source.includes('state.crossfadeEnabled')&&source.includes('state.crossfadeDuration')&&source.includes('save();renderCrossfadeSetting()'),'crossfade persistence missing'));
// Stage 1 intentionally moves audio fades away from decorative animation frames,
// which can be suspended in background tabs. P04/P06 exercise the actual guard.
test('crossfade uses independent timers and one transition owner',()=>assert(source.includes('crossfadeFrame=setTimeout(step,16)')&&source.includes('crossfadeInProgress')&&source.includes('if(selectionInProgress){')&&source.includes('playbackController.activeTransition=owner'),'crossfade timer or owner missing'));
test('manual next and dislike durations are capped',()=>assert(source.includes("event==='dislike'||event==='skip'")&&source.includes('Math.min(state.crossfadeDuration,2)'),'transition caps missing'));
test('crossfade requires preload readiness',()=>assert(source.includes('!preloadReady')&&source.includes("incoming.dataset.trackId!==String(chosen.id)"),'preload crossfade guard missing'));
test('crossfade releases old audio in finally',()=>assert(/finally\{\s*finalizePlayback\(binding\?\.event,reason,binding\);releaseMedia\(outgoing\)/.test(source)&&source.includes("element.pause();element.removeAttribute('src');element.load()"),'old audio cleanup missing'));
let cssRequest=new XMLHttpRequest();cssRequest.open('GET','../styles.css',false);cssRequest.send();let css=cssRequest.responseText;
test('orb hover preserves geometry and has smooth transitions',()=>{let hover=css.match(/\.wave-orb:hover\{([^}]*)\}/)?.[1]||'';assert(hover.includes('transform:scale(1.02)')&&!/(?:width|height|border-width)\s*:/.test(hover)&&css.includes('transition:transform 180ms ease'),'hover geometry changes')});
let failed=results.filter(x=>x.startsWith('FAIL')).length;document.querySelector('#results').textContent=`${failed?'FAILED':'PASSED'}\n${results.join('\n')}`;document.body.dataset.failed=String(failed);
