(async()=>{
await test('P01',async()=>{await start();await fillPlaybackBuffer();let full=!!playbackBuffer.next&&!!playbackBuffer.backupNext;await fillPlaybackBuffer();let retained=!!bufferFillPromise;playbackBuffer.next=null;cancelPreloadAudio();await fillPlaybackBuffer();return {pass:full&&!retained&&!!playbackBuffer.next,retainedCompletedPromise:retained,next:playbackBuffer.next?.id}});
await test('P02',async()=>{await start();await fillPlaybackBuffer();advanceBufferGeneration('test',true);let resolveHeld,held;const original=validateCandidate;validateCandidate=async(selected,rank)=>{if(!held){held=selected.track;return new Promise(resolve=>resolveHeld=resolve)}return original(selected,rank)};let fill=fillPlaybackBuffer();for(let i=0;i<20;i++)await Promise.resolve();await next();resolveHeld(held);await fill;await fillPlaybackBuffer();return {pass:current().id!==playbackBuffer.next?.id&&current().id!==playbackBuffer.backupNext?.id,held:held.id,current:current().id,next:playbackBuffer.next?.id,discarded:playbackController.events.some(x=>x.action==='STALE_RESULT_DISCARDED')}});
await test('P03',async()=>{let releases=[];validateCandidate=async selected=>new Promise(resolve=>releases.push(()=>resolve(selected.track)));let token=selectionToken(),a=choosePlayableTrack(new Set(),token),b=choosePlayableTrack(new Set(),token);for(let i=0;i<10;i++)await Promise.resolve();let keys=[...playbackController.reservations.values()].map(x=>x.track.id);releases.forEach(fn=>fn());let tracks=await Promise.all([a,b]);tracks.forEach(t=>releaseReservation(t?._reservationId));return {pass:keys.length===2&&new Set(keys).size===2&&tracks[0].id!==tracks[1].id,keys}});
await test('P04',async()=>{await start();await fillPlaybackBuffer();let calls=Array.from({length:30},()=>next());await Promise.all(calls);for(let i=0;i<80;i++)await Promise.resolve();await fillPlaybackBuffer();let rapid=playbackController.confirmedStarts.length;state.crossfadeEnabled=true;state.crossfadeDuration=1;animateCrossfade=()=>Promise.reject(Error('controlled fade failure'));await next();let unlocked=!selectionInProgress&&!crossfadeInProgress;state.crossfadeEnabled=false;await next();return {pass:rapid===3&&unlocked&&!selectionInProgress,rapidConfirmedStarts:rapid,unlocked,afterRecovery:playbackController.confirmedStarts.length}});
await test('P05',async()=>{await start();await fillPlaybackBuffer();testClock.tick(1000);const id=current().id,event=playbackController.event.id;pause();testClock.tick(4000);await play();testClock.tick(1000);await fillPlaybackBuffer();sampleListening(currentBinding());const listenedSeconds=playbackController.event.listenedSeconds;const stable=current().id===id&&playbackController.event.id===event&&waveSession.previousTracks.length===0&&playbackController.event.listenedSeconds===2&&!!playbackBuffer.next;await next();await fillPlaybackBuffer();const promotedPreload=preloadMedia?.dataset.trackId===playbackBuffer.next?.id;return {pass:stable&&promotedPreload,id,listenedSeconds,promotedPreload}});
await test('P06',async()=>{await start();await fillPlaybackBuffer();testClock.tick(1000);const old=media,ended=old.onended,outgoing=playbackController.event;state.crossfadeEnabled=true;state.crossfadeDuration=.5;let task=next();for(let i=0;i<30;i++)await Promise.resolve();testClock.tick(600);await task;const id=current().id;ended();ended();recordPlayback('next');recordPlayback('next');return {pass:current().id===id&&state.trackStats[outgoing.track.id].plays===1&&waveSession.previousTracks.filter(x=>x.playbackEventId===outgoing.id).length===1,releasedOutgoing:old.paused&&!old.src,outgoingPlays:state.trackStats[outgoing.track.id].plays,outgoingListenedSeconds:outgoing.listenedSeconds,current:id}});
await test('P07',async()=>{await start();await fillPlaybackBuffer();const currentId=current().id;advanceBufferGeneration('test',true);let held,resolveHeld;validateCandidate=async selected=>{if(!held){held=selected.track;return new Promise(resolve=>resolveHeld=resolve)}return null};let task=fillPlaybackBuffer();for(let i=0;i<20;i++)await Promise.resolve();state.genres=['Рок'];invalidateNextBuffer('genre');resolveHeld(held);await task;await fillPlaybackBuffer();let genreDiscarded=!playbackBuffer.next;const before=preloadRequestId;state.mood='Энергия';invalidateNextBuffer('mood');for(let i=0;i<40;i++){state.discovery=i;invalidateNextBuffer('discovery',true)}let pending=!!preferenceFillTimer;return {pass:genreDiscarded&&current().id===currentId&&pending&&preloadRequestId>before,current:currentId,staleNext:playbackBuffer.next?.id||null,debounced:pending}});
await test('P08',async()=>{window.testPlayError='NotAllowedError';await start();let id=current().id;recordPlayback('next');const noFake=!state.trackStats[id]?.plays&&waveSession.previousTracks.length===0&&!failedTrackIds.has(id);window.testPlayError=null;await play();testClock.tick(1000);const binding=currentBinding(),taste=JSON.stringify(state.taste);finalizePlayback(binding.event,'error',binding);const technical=state.trackStats[id]?.plays===1&&!state.trackStats[id]?.skips&&JSON.stringify(state.taste)===taste;handlePlayRejection(new DOMException('own','AbortError'),media,binding);return {pass:noFake&&technical,noFake,technical,autoplayLogged:playbackController.events.some(x=>x.action==='AUTOPLAY_BLOCKED')}});
await test('P09',()=>{let a=fixtureTrack(0),alias={...a,id:'archive:alias',source:'archive',sourceTrackId:'alias'},remix={...alias,title:a.title+' (Remix)'};waveSession.previousTracks=[a];return {pass:WaveRecommendation.isRecentlyPlayed(alias,waveSession)&&!WaveRecommendation.isRecentlyPlayed(remix,waveSession),aliasBlocked:WaveRecommendation.isRecentlyPlayed(alias,waveSession),remixBlocked:WaveRecommendation.isRecentlyPlayed(remix,waveSession)}});
await test('P10',async()=>{await start();await fillPlaybackBuffer();const first=current().id;openFullPlayer();closeFullPlayer();toggleLike();toggleLike();let reactions=waveSession.previousTracks.length===0;await next();await prev();let explicitPrevious=current().id===first;state.repeatCurrent=true;const before=playbackController.event.id;media.ended=true;media.paused=true;media.onended();for(let i=0;i<40;i++)await Promise.resolve();return {pass:reactions&&explicitPrevious&&current().id===first&&playbackController.event.id!==before&&playbackController.confirmedStarts.length===4,reactions,explicitPrevious,repeatEventChanged:playbackController.event.id!==before}});
await test('P11',async()=>{const available=fixtureTrack(0);catalog=[];await start();let empty=!selectionInProgress&&playerState==='ERROR';catalog=[available];await start();await fillPlaybackBuffer();let small=!selectionInProgress;catalog=Array.from({length:12},(_,i)=>({id:'broken:'+i,source:'fixture',title:'Broken'+i,artist:'X'+i,genre:'Pop',duration:180,stream:'/broken'}));let probes=0;validateCandidate=async()=>{probes++;return null};await start();return {pass:empty&&small&&!selectionInProgress&&probes<=8&&playerState==='ERROR',empty,small,probes,error:playerState}});
await test('P12',async()=>{waveSession.previousTracks=catalog.slice(0,25);const saved=JSON.parse(JSON.stringify(waveSession));waveSession=WaveRecommendation.createSession(saved);await start();const before=waveSession.previousTracks.length;await loadCatalog(true);pause();await play();renderPlayerUI();return {pass:before===25&&waveSession.previousTracks.length===25&&!saved.previousTracks.some(t=>t.id===current().id),recentCount:waveSession.previousTracks.length,selected:current().id}});
await test('listening excludes seek and waiting',async()=>{await start();testClock.tick(1000);seekTo(170);media.onseeking();media.onseeked();testClock.tick(1000);media.onwaiting();testClock.tick(4000);media.onplaying();testClock.tick(1000);recordPlayback('ended');const stats=state.trackStats[current().id];return {pass:playbackController.event.listenedSeconds===3&&stats.completed===0,listenedSeconds:playbackController.event.listenedSeconds,completed:stats.completed}});

await test('old fill finally cannot clear newer task',async()=>{await start();await fillPlaybackBuffer();advanceBufferGeneration('old-task',true);let held,finish;const original=validateCandidate;validateCandidate=async selected=>{if(!held){held=selected.track;return new Promise(resolve=>finish=resolve)}return original(selected,1)};const old=fillPlaybackBuffer();for(let i=0;i<20;i++)await Promise.resolve();advanceBufferGeneration('new-task',true);let finishNew;validateCandidate=async selected=>new Promise(resolve=>finishNew=()=>resolve(selected.track));const newer=fillPlaybackBuffer();for(let i=0;i<20;i++)await Promise.resolve();finish(held);await old;const preserved=bufferFillPromise===newer;advanceBufferGeneration('cleanup',true);finishNew();await newer;return {pass:preserved,preserved}});
await test('stale media callbacks cannot advance replacement',async()=>{await start();await fillPlaybackBuffer();const outgoing=media,lateError=outgoing.onerror,lateEnded=outgoing.onended,latePlaying=outgoing.onplaying;await next();const id=current().id,count=playbackController.confirmedStarts.length;lateError();lateEnded();latePlaying();for(let i=0;i<40;i++)await Promise.resolve();return {pass:current().id===id&&playbackController.confirmedStarts.length===count,id,confirmedStarts:count}});
await test('automatic errors share retry budget',async()=>{window.testPlayError='NotSupportedError';await start();for(let i=0;i<200;i++)await Promise.resolve();const attempts=playbackRetryCount;return {pass:attempts===MAX_PLAYBACK_RETRIES&&!selectionInProgress&&waveSession.previousTracks.length===0&&state.history.length===0,attempts,confirmed:playbackController.confirmedStarts.length,state:playerState}});
await test('Previous walks two existing positions',async()=>{await start();await fillPlaybackBuffer();const first=current().id;await next();await fillPlaybackBuffer();await next();await prev();await prev();return {pass:current().id===first&&index===0,first,current:current().id,index}});
await test('diagnostics has selectable clipboard fallback',async()=>{Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw Error('controlled denied')}},configurable:true});await copyWaveDiagnostics();const field=document.querySelector('#diagnosticText'),text=field.value;return {pass:!field.hidden&&field.selectionEnd===text.length&&!text.includes('streamUrl')&&!text.includes('localStorage'),selected:field.selectionEnd,length:text.length}});
await test('preference change during Next keeps one fresh transition',async()=>{await start();await fillPlaybackBuffer();const before=current().id;advanceBufferGeneration('test',true);let held,resolveHeld;const original=validateCandidate;validateCandidate=async(selected,rank,token)=>{if(!held){held=selected.track;return new Promise(resolve=>resolveHeld=resolve)}return original(selected,rank,token)};const transition=next();for(let i=0;i<20;i++)await Promise.resolve();state.discovery=70;WaveRecommendation.updateWavePreferences(waveSession,{noveltyLevel:.7});invalidateNextBuffer('discovery',true);resolveHeld(held);await transition;for(let i=0;i<150;i++)await Promise.resolve();await fillPlaybackBuffer();return {pass:current().id!==before&&playbackController.confirmedStarts.length===2&&!selectionInProgress,before,current:current().id,confirmedStarts:playbackController.confirmedStarts.length}});
for(const seed of [1,42,20260929]){
  try{const evidence=await inApp(async()=>{await start();for(let i=1;i<60;i++){await fillPlaybackBuffer();testClock.tick(1000);await next()}await fillPlaybackBuffer();const ids=playbackController.confirmedStarts.map(x=>x.trackKey);let min=null;const seen=new Map();ids.forEach((id,i)=>{if(seen.has(id))min=min===null?i-seen.get(id):Math.min(min,i-seen.get(id));seen.set(id,i)});return {ids,unique:new Set(ids).size,first25Unique:new Set(ids.slice(0,25)).size,minimumRepeatDistance:min,locked:selectionInProgress,reserved:playbackController.reservations.size}},seed);const pass=evidence.ids.length===60&&evidence.first25Unique===25&&(evidence.minimumRepeatDistance===null||evidence.minimumRepeatDistance>25)&&!evidence.locked;sequences.push({seed,pass,...evidence});results.push({id:'sequence-'+seed,pass})}catch(error){results.push({id:'sequence-'+seed,pass:false,error:error.message})}
}
window.controllerTestResults={results,sequences};document.body.dataset.failed=String(results.filter(x=>!x.pass).length);document.querySelector('#results').textContent=JSON.stringify(window.controllerTestResults,null,2);
})().catch(error=>{document.body.dataset.failed='1';document.querySelector('#results').textContent=error.stack});
