const results=[];
function test(name,fn){try{fn();results.push(`PASS ${name}`)}catch(error){results.push(`FAIL ${name}: ${error.message}`)}}
function assert(condition,message){if(!condition)throw Error(message)}
const tracks={
  calmFamiliar:{id:'calm-old',title:'Old Calm',artist:'Soft A',genre:'Lo-Fi',mood:'Peaceful',bpm:72,releaseDate:'2018-01-01'},
  calmNew:{id:'calm-new',title:'New Calm',artist:'Soft B',genre:'Ambient',mood:'Chill',bpm:68,releaseDate:'2026-08-01'},
  energyFamiliar:{id:'energy-old',title:'Old Energy',artist:'Fast A',genre:'Dance',mood:'Energizing',bpm:130,releaseDate:'2019-01-01'},
  energyNew:{id:'energy-new',title:'New Energy',artist:'Fast B',genre:'Electronic',mood:'Upbeat',bpm:128,releaseDate:'2026-08-15'},
  experiment:{id:'wild',title:'Wild',artist:'Other',genre:'Death Metal',mood:'Aggressive',bpm:190,releaseDate:'2026-09-01'}
};
function fixture(){return {likes:[tracks.calmFamiliar,tracks.energyFamiliar],taste:{genres:{'Lo-Fi':3,Dance:3},artists:{'Soft A':3,'Fast A':3}},trackStats:{'calm-old':{plays:8,completed:7,skips:0,likes:1,dislikes:0,lastPlayedAt:'2026-07-01',recentPlayDates:[]},'energy-old':{plays:7,completed:6,skips:0,likes:1,dislikes:0,lastPlayedAt:'2026-07-01',recentPlayDates:[]}}}}
function score(track,mood,novelty,state=fixture(),previousTracks=[]){let session=WaveRecommendation.createSession({currentMood:mood,noveltyLevel:novelty,previousTracks});return WaveRecommendation.scoreTrack(track,{state,session,selectedGenres:['Lo-Fi','Ambient','Dance','Electronic']})}
test('1 calm + novelty 0 prefers familiar calm',()=>assert(score(tracks.calmFamiliar,'Спокойствие',0).finalScore>score(tracks.calmNew,'Спокойствие',0).finalScore,'new calm outranked familiar'));
test('2 calm + novelty 1 prefers new calm',()=>assert(score(tracks.calmNew,'Спокойствие',1).finalScore>score(tracks.calmFamiliar,'Спокойствие',1).finalScore,'familiar calm outranked new'));
test('3 energetic + novelty 0 prefers familiar energetic',()=>assert(score(tracks.energyFamiliar,'Энергия',0).finalScore>score(tracks.energyNew,'Энергия',0).finalScore,'new energy outranked familiar'));
test('4 energetic + novelty 1 prefers new energetic',()=>assert(score(tracks.energyNew,'Энергия',1).finalScore>score(tracks.energyFamiliar,'Энергия',1).finalScore,'familiar energy outranked new'));
test('mood is soft, not a hard filter',()=>assert(score(tracks.experiment,'Спокойствие',1).moodScore>0,'mismatched mood was excluded'));
test('5 repeated early skips lower future score',()=>{let state=fixture(),session=WaveRecommendation.createSession({currentMood:'Спокойствие',noveltyLevel:.5});let before=WaveRecommendation.scoreTrack(tracks.calmNew,{state,session,selectedGenres:['Ambient']});for(let i=0;i<3;i++)WaveRecommendation.recordEvent(state,session,tracks.calmNew,'skip',.05);let after=WaveRecommendation.scoreTrack(tracks.calmNew,{state,session,selectedGenres:['Ambient']});assert(after.skipPenalty>before.skipPenalty&&after.finalScore<before.finalScore,'skip signal did not lower score')});
test('6 like raises preference for future selection',()=>{let state=fixture(),session=WaveRecommendation.createSession({currentMood:'Спокойствие',noveltyLevel:.5}),context={state,session,selectedGenres:[]};let before=WaveRecommendation.scoreTrack(tracks.calmNew,context);WaveRecommendation.recordEvent(state,session,tracks.calmNew,'like',.4);let after=WaveRecommendation.scoreTrack(tracks.calmNew,context);assert(after.preferenceScore>before.preferenceScore,'like did not raise preference')});
test('7 recently played favorite receives repeat penalty',()=>{let previous=[{id:'calm-old',artist:'Soft A',album:'',genre:'Lo-Fi',playedAt:new Date().toISOString()}],recent=score(tracks.calmFamiliar,'Спокойствие',0,fixture(),previous),alternative=score(tracks.calmNew,'Спокойствие',0,fixture(),previous);assert(recent.repeatPenalty>0&&recent.finalScore<alternative.finalScore,'favorite repeated immediately')});
test('mood weight changes ranking',()=>{let state={likes:[],taste:{genres:{},artists:{}},trackStats:{}},session=WaveRecommendation.createSession({currentMood:'Спокойствие',noveltyLevel:.5}),context={state,session,selectedGenres:[]},calm={id:'m1',title:'Twin',artist:'A',genre:'Pop',mood:'Peaceful',bpm:72},energy={...calm,id:'m2',mood:'Energizing',bpm:132},old=WaveRecommendationConfig().weights.mood;WAVE_RECOMMENDATION_CONFIG.weights.mood=0;let zero=WaveRecommendation.scoreTrack(calm,context).finalScore-WaveRecommendation.scoreTrack(energy,context).finalScore;WAVE_RECOMMENDATION_CONFIG.weights.mood=.8;let weighted=WaveRecommendation.scoreTrack(calm,context).finalScore-WaveRecommendation.scoreTrack(energy,context).finalScore;WAVE_RECOMMENDATION_CONFIG.weights.mood=old;assert(weighted>zero+.05,'mood weight did not change ranking')});
test('novelty weight changes ranking',()=>{let state={likes:[],taste:{genres:{},artists:{}},trackStats:{old:{plays:8,completed:6,skips:0,lastPlayedAt:'2026-09-01',recentPlayDates:[]}}},session=WaveRecommendation.createSession({currentMood:'Спокойствие',noveltyLevel:1}),context={state,session,selectedGenres:[]},oldTrack={id:'old',title:'Same',artist:'A',genre:'Ambient',mood:'Peaceful'},newTrack={...oldTrack,id:'new'},config=WaveRecommendationConfig(),oldWeight=config.weights.userNovelty,oldMix=JSON.parse(JSON.stringify(config.mix));Object.values(config.mix).forEach(x=>{x.start=.5;x.end=.5});config.weights.userNovelty=0;let zero=WaveRecommendation.scoreTrack(newTrack,context).finalScore-WaveRecommendation.scoreTrack(oldTrack,context).finalScore;config.weights.userNovelty=.8;let weighted=WaveRecommendation.scoreTrack(newTrack,context).finalScore-WaveRecommendation.scoreTrack(oldTrack,context).finalScore;config.weights.userNovelty=oldWeight;config.mix=oldMix;assert(weighted>zero+.05,'novelty weight did not change ranking')});
test('load does not write listening history',()=>{let request=new XMLHttpRequest();request.open('GET','../app.js',false);request.send();let body=request.responseText.match(/function load\(\)\{([\s\S]*?)\}\nfunction updateMediaSession/)?.[1]||'';assert(!body.includes('state.history'),'load still mutates history')});
test('early skip writes one non-duplicated history entry',()=>{let state={likes:[],history:[],taste:{genres:{},artists:{}},trackStats:{}},session=WaveRecommendation.createSession(),track={id:'skip-me',title:'Skip',artist:'A',genre:'Pop',duration:100};WaveRecommendation.recordEvent(state,session,track,'skip',{progressRatio:.05,listenedSeconds:5});WaveRecommendation.recordEvent(state,session,track,'skip',{progressRatio:.05,listenedSeconds:5});assert(state.history.length===1&&state.history[0].id==='skip-me','early skip history is missing or duplicated')});
test('one dislike barely affects the rest of its genre',()=>{let state={likes:[],dislikes:[],taste:{genres:{},artists:{}},trackStats:{}},session=WaveRecommendation.createSession(),bad={id:'bad',title:'Bad',artist:'A',genre:'Rock'},other={id:'other',title:'Other',artist:'B',genre:'Rock'},context={state,session,selectedGenres:[]},before=WaveRecommendation.scoreTrack(other,context).preferenceScore;WaveRecommendation.recordEvent(state,session,bad,'dislike',{progressRatio:.05,listenedSeconds:5});let after=WaveRecommendation.scoreTrack(other,context).preferenceScore;assert(before-after<.03,'single dislike suppressed the whole genre')});
test('disliked track receives a large direct penalty',()=>{let state={likes:[],dislikes:[],taste:{genres:{},artists:{}},trackStats:{}},session=WaveRecommendation.createSession(),track={id:'bad-direct',title:'Bad',artist:'A',genre:'Rock'},context={state,session,selectedGenres:[]};WaveRecommendation.recordEvent(state,session,track,'dislike',{progressRatio:.05,listenedSeconds:5});let scored=WaveRecommendation.scoreTrack(track,context);assert(scored.skipPenalty>=WAVE_RECOMMENDATION_CONFIG.feedback.dislikeTrackPenalty,'direct dislike penalty is too small')});
let failed=results.filter(x=>x.startsWith('FAIL')).length;document.querySelector('#results').textContent=`${failed?'FAILED':'PASSED'}\n${results.join('\n')}`;document.body.dataset.failed=String(failed);
function WaveRecommendationConfig(){return window.WAVE_RECOMMENDATION_CONFIG}
