const results=[];
function test(name,fn){try{fn();results.push(`PASS ${name}`)}catch(error){results.push(`FAIL ${name}: ${error.message}`)}}
function assert(condition,message){if(!condition)throw Error(message)}
const tracks={
  calmFamiliar:{id:'calm-old',title:'Old Calm',artist:'Soft A',genre:'Lo-Fi',mood:'Peaceful',bpm:72,releaseDate:'2018-01-01'},
  calmNew:{id:'calm-new',title:'New Calm',artist:'Soft B',genre:'Ambient',mood:'Chill',bpm:68,releaseDate:'2026-08-01'},
  energyFamiliar:{id:'energy-old',title:'Old Energy',artist:'Fast A',genre:'Dance',mood:'Energizing',bpm:130,releaseDate:'2019-01-01'},
  energyNew:{id:'energy-new',title:'New Energy',artist:'Fast B',genre:'Electronic',mood:'Upbeat',bpm:128,releaseDate:'2026-08-15'},
  experiment:{id:'wild',title:'Wild',artist:'Other',genre:'Death Metal',mood:'Aggressive',bpm:190,releaseDate:'2026-09-01'}
};
function fixture(){return {likes:[tracks.calmFamiliar,tracks.energyFamiliar],taste:{genres:{'Lo-Fi':3,Dance:3},artists:{'Soft A':3,'Fast A':3}},trackStats:{'calm-old':{plays:8,completed:7,skips:0,likes:1,dislikes:0,lastPlayedAt:'2026-07-01',recentPlayDates:[]},'energy-old':{plays:7,completed:6,skips:0,likes:1,dislikes:0,lastPlayedAt:'2026-07-01',recentPlayDates:[]}}}}
function score(track,mood,novelty,state=fixture(),previousTracks=[]){let session=WaveRecommendation.createSession({currentMood:mood,noveltyLevel:novelty,previousTracks});return WaveRecommendation.scoreTrack(track,{state,session,selectedGenres:['Lo-Fi','Ambient','Dance','Electronic']})}
test('1 calm + novelty 0 prefers familiar calm',()=>assert(score(tracks.calmFamiliar,'Спокойствие',0).finalScore>score(tracks.calmNew,'Спокойствие',0).finalScore,'new calm outranked familiar'));
test('2 calm + novelty 1 prefers new calm',()=>assert(score(tracks.calmNew,'Спокойствие',1).finalScore>score(tracks.calmFamiliar,'Спокойствие',1).finalScore,'familiar calm outranked new'));
test('3 energetic + novelty 0 prefers familiar energetic',()=>assert(score(tracks.energyFamiliar,'Энергия',0).finalScore>score(tracks.energyNew,'Энергия',0).finalScore,'new energy outranked familiar'));
test('4 energetic + novelty 1 prefers new energetic',()=>assert(score(tracks.energyNew,'Энергия',1).finalScore>score(tracks.energyFamiliar,'Энергия',1).finalScore,'familiar energy outranked new'));
test('mood is soft, not a hard filter',()=>assert(score(tracks.experiment,'Спокойствие',1).moodScore>0,'mismatched mood was excluded'));
test('5 repeated early skips lower future score',()=>{let state=fixture(),session=WaveRecommendation.createSession({currentMood:'Спокойствие',noveltyLevel:.5});let before=WaveRecommendation.scoreTrack(tracks.calmNew,{state,session,selectedGenres:['Ambient']});for(let i=0;i<3;i++)WaveRecommendation.recordEvent(state,session,tracks.calmNew,'skip',.05);let after=WaveRecommendation.scoreTrack(tracks.calmNew,{state,session,selectedGenres:['Ambient']});assert(after.skipPenalty>before.skipPenalty&&after.finalScore<before.finalScore,'skip signal did not lower score')});
test('6 like raises preference for future selection',()=>{let state=fixture(),session=WaveRecommendation.createSession({currentMood:'Спокойствие',noveltyLevel:.5}),context={state,session,selectedGenres:[]};let before=WaveRecommendation.scoreTrack(tracks.calmNew,context);WaveRecommendation.recordEvent(state,session,tracks.calmNew,'like',.4);let after=WaveRecommendation.scoreTrack(tracks.calmNew,context);assert(after.preferenceScore>before.preferenceScore,'like did not raise preference')});
test('7 recently played favorite receives repeat penalty',()=>{let previous=[{id:'calm-old',artist:'Soft A',album:'',genre:'Lo-Fi',playedAt:new Date().toISOString()}],recent=score(tracks.calmFamiliar,'Спокойствие',0,fixture(),previous),alternative=score(tracks.calmNew,'Спокойствие',0,fixture(),previous);assert(recent.repeatPenalty>0&&recent.finalScore<alternative.finalScore,'favorite repeated immediately')});
test('mood weight changes ranking',()=>{let state={likes:[],taste:{genres:{},artists:{}},trackStats:{}},session=WaveRecommendation.createSession({currentMood:'Спокойствие',noveltyLevel:.5}),context={state,session,selectedGenres:[]},calm={id:'m1',title:'Twin',artist:'A',genre:'Pop',mood:'Peaceful',bpm:72},energy={...calm,id:'m2',mood:'Energizing',bpm:132},old=WaveRecommendationConfig().weights.mood;WAVE_RECOMMENDATION_CONFIG.weights.mood=0;let zero=WaveRecommendation.scoreTrack(calm,context).finalScore-WaveRecommendation.scoreTrack(energy,context).finalScore;WAVE_RECOMMENDATION_CONFIG.weights.mood=.8;let weighted=WaveRecommendation.scoreTrack(calm,context).finalScore-WaveRecommendation.scoreTrack(energy,context).finalScore;WAVE_RECOMMENDATION_CONFIG.weights.mood=old;assert(weighted>zero+.05,'mood weight did not change ranking')});
test('novelty weight changes ranking',()=>{let state={likes:[],taste:{genres:{},artists:{}},trackStats:{old:{plays:8,completed:6,skips:0,lastPlayedAt:'2026-09-01',recentPlayDates:[]}}},session=WaveRecommendation.createSession({currentMood:'Спокойствие',noveltyLevel:1}),context={state,session,selectedGenres:[]},oldTrack={id:'old',title:'Same',artist:'A',genre:'Ambient',mood:'Peaceful'},newTrack={...oldTrack,id:'new'},config=WaveRecommendationConfig(),oldWeight=config.weights.userNovelty,oldMix=JSON.parse(JSON.stringify(config.mix));Object.values(config.mix).forEach(x=>{x.start=.5;x.end=.5});config.weights.userNovelty=0;let zero=WaveRecommendation.scoreTrack(newTrack,context).finalScore-WaveRecommendation.scoreTrack(oldTrack,context).finalScore;config.weights.userNovelty=.8;let weighted=WaveRecommendation.scoreTrack(newTrack,context).finalScore-WaveRecommendation.scoreTrack(oldTrack,context).finalScore;config.weights.userNovelty=oldWeight;config.mix=oldMix;assert(weighted>zero+.05,'novelty weight did not change ranking')});
test('load does not write listening history',()=>{let request=new XMLHttpRequest();request.open('GET','../app.js',false);request.send();let body=request.responseText.match(/function load\(\)\{([\s\S]*?)\}\nfunction updateMediaSession/)?.[1]||'';assert(!body.includes('state.history'),'load still mutates history')});
test('early skip writes one non-duplicated history entry',()=>{let state={likes:[],history:[],taste:{genres:{},artists:{}},trackStats:{}},session=WaveRecommendation.createSession(),track={id:'skip-me',title:'Skip',artist:'A',genre:'Pop',duration:100};WaveRecommendation.recordEvent(state,session,track,'skip',{progressRatio:.05,listenedSeconds:5});WaveRecommendation.recordEvent(state,session,track,'skip',{progressRatio:.05,listenedSeconds:5});assert(state.history.length===1&&state.history[0].id==='skip-me','early skip history is missing or duplicated')});
test('one dislike barely affects the rest of its genre',()=>{let state={likes:[],dislikes:[],taste:{genres:{},artists:{}},trackStats:{}},session=WaveRecommendation.createSession(),bad={id:'bad',title:'Bad',artist:'A',genre:'Rock'},other={id:'other',title:'Other',artist:'B',genre:'Rock'},context={state,session,selectedGenres:[]},before=WaveRecommendation.scoreTrack(other,context).preferenceScore;WaveRecommendation.recordEvent(state,session,bad,'dislike',{progressRatio:.05,listenedSeconds:5});let after=WaveRecommendation.scoreTrack(other,context).preferenceScore;assert(before-after<.03,'single dislike suppressed the whole genre')});
test('one early skip does not make a track familiar',()=>{let state={likes:[],history:[],dislikes:[],taste:{genres:{},artists:{}},trackStats:{}},session=WaveRecommendation.createSession(),track={id:'early-skip',title:'Skipped',artist:'A',genre:'Pop',duration:100};WaveRecommendation.recordEvent(state,session,track,'skip',{progressRatio:.05,listenedSeconds:5});let scored=WaveRecommendation.scoreTrack(track,{state,session,selectedGenres:[]});assert(scored.selectionType!=='FAMILIAR','early skip incorrectly became familiar')});
test('disliked track receives a large direct penalty',()=>{let state={likes:[],dislikes:[],taste:{genres:{},artists:{}},trackStats:{}},session=WaveRecommendation.createSession(),track={id:'bad-direct',title:'Bad',artist:'A',genre:'Rock'},context={state,session,selectedGenres:[]};WaveRecommendation.recordEvent(state,session,track,'dislike',{progressRatio:.05,listenedSeconds:5});let scored=WaveRecommendation.scoreTrack(track,context);assert(scored.skipPenalty>=WAVE_RECOMMENDATION_CONFIG.feedback.dislikeTrackPenalty,'direct dislike penalty is too small')});
test('technical playback error is not user feedback',()=>{let state={likes:[],history:[],taste:{genres:{Rock:2},artists:{A:3}},trackStats:{}},before=JSON.stringify(state),session=WaveRecommendation.createSession(),track={id:'broken',title:'Broken',artist:'A',genre:'Rock'};WaveRecommendation.recordEvent(state,session,track,'error',{progressRatio:0,listenedSeconds:0});assert(JSON.stringify(state)===before&&session.previousTracks.length===0,'error changed taste, stats, history, or session listening history')});
test('playback retries are capped and do not record error',()=>{let request=new XMLHttpRequest();request.open('GET','../app.js',false);request.send();let source=request.responseText;assert(source.includes('const MAX_PLAYBACK_RETRIES=2')&&source.includes("next('error',true)")&&!source.includes('streamFailures<8'), 'playback retry guard is missing')});
test('ranked candidates use the existing score order',()=>{let state=fixture(),session=WaveRecommendation.createSession({currentMood:'Спокойствие',noveltyLevel:.5}),context={state,session,selectedGenres:['Lo-Fi','Ambient']},ranked=WaveRecommendation.getRankedCandidates(Object.values(tracks),context,3);assert(ranked.length===3&&ranked.every((x,i)=>i===0||ranked[i-1].finalScore>=x.finalScore),'candidate ranking is not sorted by existing finalScore')});
function seededRandom(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}}
function sequenceCatalog(size=60){return Array.from({length:size},(_,i)=>({id:`sequence-${i}`,title:`Track ${i}`,artist:`Artist ${i%18}`,album:`Album ${i%24}`,genre:i%3?'Ambient':'Pop',mood:i%4?'Peaceful':'Dreamy',bpm:68+i%12,releaseDate:`2026-08-${String(i%28+1).padStart(2,'0')}`}))}
function buildSequence(seed,count=30,catalog=sequenceCatalog()){let random=seededRandom(seed),state={likes:[],history:[],dislikes:[],trackStats:{},taste:{genres:{Ambient:1},artists:{}}},session=WaveRecommendation.createSession({currentMood:'Спокойствие',noveltyLevel:.5}),context={state,session,selectedGenres:['Ambient','Pop']},ids=[];for(let i=0;i<count;i++){let selected=WaveRecommendation.getNextTrack(catalog,context,random);assert(selected,'sequence selection returned no track');ids.push(selected.track.id);WaveRecommendation.recordEvent(state,session,selected.track,'ended',{progressRatio:1,listenedSeconds:selected.track.duration||180})}return ids}
function minimumRepeatDistance(ids){let seen=new Map(),minimum=Infinity;ids.forEach((id,index)=>{if(seen.has(id))minimum=Math.min(minimum,index-seen.get(id));seen.set(id,index)});return minimum}
test('hard anti-repeat keeps the first 20 recommendations unique',()=>{let ids=buildSequence(7);assert(new Set(ids.slice(0,20)).size===20,'a track repeated inside the first 20 selections');assert(minimumRepeatDistance(ids)>WAVE_RECOMMENDATION_CONFIG.hardTrackBlock,'a track repeated inside hardTrackBlock')});
test('old eight-track cycle cannot return A after A-H',()=>{let catalog=sequenceCatalog(30),state={likes:[],history:[],dislikes:[],trackStats:{},taste:{genres:{},artists:{}}},session=WaveRecommendation.createSession({previousTracks:catalog.slice(0,8).map(track=>({id:track.id,artist:track.artist,genre:track.genre,event:'ended'}))}),context={state,session,selectedGenres:[]},eligible=WaveRecommendation.eligibleCandidates(catalog,session).candidates.map(WaveRecommendation.idOf);assert(!eligible.includes(catalog[0].id),'A became eligible immediately after the old 8-track window')});
test('weighted sampling produces different non-cyclic sequences',()=>{let first=buildSequence(11),second=buildSequence(29);assert(first.join(',')!==second.join(','),'different random seeds produced an identical sequence');assert(new Set(first).size>=26&&new Set(second).size>=26,'30 selections did not contain enough unique tracks')});
test('higher scored tracks remain more likely',()=>{let catalog=sequenceCatalog(50),topWins=0,bottomWins=0;for(let seed=1;seed<=120;seed++){let state={likes:[],history:[],trackStats:{},taste:{genres:{Ambient:3},artists:{}}},session=WaveRecommendation.createSession({currentMood:'Спокойствие',noveltyLevel:.5}),context={state,session,selectedGenres:['Ambient']},ranking=WaveRecommendation.getRankedCandidates(catalog,context,50),selected=WaveRecommendation.getNextTrack(catalog,context,seededRandom(seed)),rank=ranking.findIndex(x=>x.track.id===selected.track.id);if(rank<12)topWins++;if(rank>=36)bottomWins++}assert(topWins>bottomWins,'low-score tracks were at least as likely as the top group')});
test('novelty midpoint does not let familiar tracks take over',()=>{let catalog=sequenceCatalog(60),state={likes:[],history:[],dislikes:[],trackStats:{},taste:{genres:{Ambient:1},artists:{}}};catalog.slice(0,30).forEach(track=>state.trackStats[track.id]={plays:2,completed:1,skips:0,lastPlayedAt:'2026-01-01',recentPlayDates:[]});let session=WaveRecommendation.createSession({currentMood:'Спокойствие',noveltyLevel:.5}),context={state,session,selectedGenres:['Ambient','Pop']},random=seededRandom(7),familiar=0;for(let i=0;i<30;i++){let selected=WaveRecommendation.getNextTrack(catalog,context,random);if(selected.selectionType==='FAMILIAR')familiar++;WaveRecommendation.recordEvent(state,session,selected.track,'ended',{progressRatio:1,listenedSeconds:180})}assert(familiar>=12&&familiar<=20,`midpoint familiar count was ${familiar}/30`)});
let failed=results.filter(x=>x.startsWith('FAIL')).length;document.querySelector('#results').textContent=`${failed?'FAILED':'PASSED'}\n${results.join('\n')}`;document.body.dataset.failed=String(failed);
function WaveRecommendationConfig(){return window.WAVE_RECOMMENDATION_CONFIG}
