(async()=>{
await test('safe shared time formatter',()=>{const inputs=[4,76.355937,3599,3600,3737,NaN,Infinity,-10,undefined,null],expected=['0:04','1:16','59:59','1:00:00','1:02:17','0:00','0:00','0:00','0:00','0:00'];return {pass:inputs.every((x,i)=>fmt(x)===expected[i]),values:inputs.map(fmt)}});
await test('first sound precedes slow catalog completion',async()=>{catalog=[];loadCatalog=originalLoadCatalog;let release,slowFinished=false;const tracks=Array.from({length:30},(_,i)=>fixtureTrack(i)).filter(Boolean);const items=Array.from({length:30},(_,i)=>WaveTrackModel.normalizeTrack({id:'fixture:progressive'+i,source:'fixture',title:'Progressive '+i,artist:'Artist '+i,genre:'Pop',duration:180,stream:'/fixture/'+i},'fixture'));const fast={id:'fast',getTrendingTracks:async()=>items,getLatestTracks:async()=>items,getTracksByGenre:async()=>items},slow={id:'slow',getTrendingTracks:()=>new Promise(resolve=>release=()=>{slowFinished=true;resolve([])}),getLatestTracks:async()=>[],getTracksByGenre:async()=>[]};const manager=new WaveSourceManager([fast,slow]);sourceManager.getCatalog=manager.getCatalog.bind(manager);sourceManager.searchTracks=async()=>[];await start();const playedBeforeSlow=playerState==='PLAYING'&&!slowFinished;const completion=catalogTask?.complete;release();await completion;return {pass:playedBeforeSlow&&catalog.length===30,playedBeforeSlow,catalogSize:catalog.length}});
await test('cold start and cached repeat reuse catalog',async()=>{let calls=0;const original=sourceManager.getCatalog.bind(sourceManager);catalogLoadedAt=Date.now();loadCatalog=originalLoadCatalog;sourceManager.getCatalog=async options=>{calls++;return original(options)};await start();pause();await play();await start();return {pass:playerState==='PLAYING'&&calls===0&&playbackController.confirmedStarts.length===2,catalogFetches:calls}});
await test('slow validation does not delay good sibling and releases reservations',async()=>{playbackController.validationConcurrency=2;let calls=0,cancelled=false;validateCandidate=async(selected,rank,token,signal)=>{if(++calls===1)return new Promise(resolve=>signal.addEventListener('abort',()=>{cancelled=true;resolve(null)},{once:true}));return selected.track};const chosen=await choosePlayableTrack();releaseReservation(chosen?._reservationId);await Promise.resolve();return {pass:!!chosen&&cancelled&&calls===2&&playbackController.reservations.size===0,calls,cancelled,reservations:playbackController.reservations.size}});
await test('two bad candidates continue within budget',async()=>{playbackController.validationConcurrency=2;let calls=0;validateCandidate=async selected=>++calls<=2?null:selected.track;const chosen=await choosePlayableTrack();releaseReservation(chosen?._reservationId);await Promise.resolve();return {pass:!!chosen&&calls>=3&&calls<=4&&playbackController.reservations.size===0,calls}});
await test('timeout sibling permits next candidate',async()=>{playbackController.validationConcurrency=2;let calls=0;sourceManager.resolveTrack=async(track,{signal}={})=>{if(++calls===1)throw new DOMException('controlled source timeout','TimeoutError');return track};const chosen=await choosePlayableTrack();releaseReservation(chosen?._reservationId);return {pass:!!chosen&&calls>=2,failures:failedTrackIds.size}});
await test('preload requires media data rather than metadata',()=>{const Base=Audio;Audio=class extends Base{load(){this.readyState=1;this.buffered={length:0};this.onloadedmetadata?.()}};const track=fixtureTrack(0);playbackBuffer.next=track;preloadTrack(track,preloadRequestId);const metadata=preloadReady;preloadMedia.readyState=2;preloadMedia.onloadeddata();const data=preloadReady;preloadMedia.readyState=3;preloadMedia.buffered={length:1,start:()=>0,end:()=>.25};preloadMedia.oncanplay();return {pass:!metadata&&!data&&preloadReady,metadata,data,canplay:preloadReady}});
await test('prepared next bypasses validation and promotes backup',async()=>{await start();await fillPlaybackBuffer();const ready=playbackBuffer.next.id,backup=playbackBuffer.backupNext.id;const original=validateCandidate;let validatedPrepared=0;validateCandidate=async(...args)=>{if(args[0].track.id===ready)validatedPrepared++;return original(...args)};await next();await fillPlaybackBuffer();return {pass:current().id===ready&&playbackBuffer.next.id===backup&&!!playbackBuffer.backupNext&&validatedPrepared===0,current:current().id,next:playbackBuffer.next.id,validatedPrepared}});
await test('ten rapid Next with concurrent validation serialize',async()=>{playbackController.validationConcurrency=2;await start();await fillPlaybackBuffer();await Promise.all(Array.from({length:10},()=>next()));for(let i=0;i<200;i++)await Promise.resolve();await fillPlaybackBuffer();return {pass:playbackController.confirmedStarts.length===3&&!selectionInProgress&&!crossfadeInProgress&&playbackController.reservations.size===0,starts:playbackController.confirmedStarts.length,reservations:playbackController.reservations.size}});
await test('ended promotes buffer once',async()=>{await start();await fillPlaybackBuffer();const before=playbackBuffer.next.id,old=media,ended=old.onended;testClock.tick(1000);old.ended=true;old.paused=true;ended();ended();for(let i=0;i<200;i++)await Promise.resolve();await fillPlaybackBuffer();return {pass:current().id===before&&playbackController.confirmedStarts.length===2,starts:playbackController.confirmedStarts.length}});
window.controllerTestResults={results};document.body.dataset.failed=String(results.filter(x=>!x.pass).length);document.querySelector('#results').textContent=JSON.stringify(window.controllerTestResults,null,2);
})().catch(error=>{document.body.dataset.failed='1';document.querySelector('#results').textContent=error.stack});
