(async()=>{
  const results=[],wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),assert=(value,message)=>{if(!value)throw Error(message)};
  async function test(name,fn){try{const evidence=await fn();results.push({name,pass:true,evidence})}catch(error){results.push({name,pass:false,error:error.message})}}
  let analyser=null;const backdrop=new WaveBackdrop(document.querySelector('#canvas'),()=>analyser);
  await test('procedural wave flows without translating its canvas',async()=>{backdrop.setState('PLAYING');const before=backdrop.point(180,4),rect=backdrop.canvas.getBoundingClientRect();await wait(400);const after=backdrop.point(180,4),next=backdrop.canvas.getBoundingClientRect();assert(before!==after&&rect.x===next.x&&rect.y===next.y,'geometry or fixed position');return {before,after,mode:backdrop.debug().mode}});
  await test('existing analyser smoothly drives bass mid high and RMS',async()=>{analyser={frequencyBinCount:512,fftSize:1024,context:{sampleRate:48000},getByteFrequencyData(array){array.fill(170)},getByteTimeDomainData(array){for(let i=0;i<array.length;i++)array[i]=128+Math.round(Math.sin(i*.13)*22)}};await wait(500);const bands={...backdrop.bands};assert(Object.values(bands).every(x=>x>0)&&backdrop.debug().mode==='analyser','analyser not sampled');return {bands}});
  await test('pause releases energy gradually',async()=>{const energy=backdrop.bands.rms;backdrop.setState('PAUSED');await wait(80);const early=backdrop.bands.rms;await wait(900);const late=backdrop.bands.rms;assert(early>0&&early<energy&&late<early&&backdrop.activity<.6,'pause did not fade');return {energy,early,late}});
  await test('hidden document stops animation and resumes on visibility',async()=>{let hidden=true;Object.defineProperty(document,'hidden',{get:()=>hidden,configurable:true});document.dispatchEvent(new Event('visibilitychange'));const frames=backdrop.frames;await wait(100);assert(!backdrop.frame&&backdrop.frames===frames,'hidden frames continued');hidden=false;document.dispatchEvent(new Event('visibilitychange'));await wait(100);assert(backdrop.frames>frames,'visible did not resume');return {frames,after:backdrop.frames}});
  await test('decorative layer never allocates playback elements',()=>{assert(!document.querySelector('audio,video'),'visualizer created media');return {mediaElements:0}});
  backdrop.suspend();document.body.dataset.failed=String(results.filter(x=>!x.pass).length);document.querySelector('#results').textContent=JSON.stringify(results,null,2);
})().catch(error=>{document.body.dataset.failed='1';document.querySelector('#results').textContent=error.stack});
