(function(root){
  class SourceManager{
    constructor(sources=Object.values(root.WaveSources||{}),config=root.WaveSourceConfig||{}){this.config=config;this.sources=new Map(sources.map(x=>[x.id,x]));this.metadataCache=new Map();this.streamCache=new Map();this.health=new Map(sources.map(x=>[x.id,{successCount:0,failureCount:0,averageResolveTime:0}]))}
    enabled(){return [...this.sources.values()].filter(x=>!x.enabled||x.enabled())}withTimeout(task,ms=this.config.REQUEST_TIMEOUT_MS||6000,parentSignal=null){let controller=new AbortController(),timer=setTimeout(()=>controller.abort('source timeout'),ms);let abort=()=>controller.abort(parentSignal?.reason);if(parentSignal?.aborted)abort();else parentSignal?.addEventListener('abort',abort,{once:true});return Promise.resolve().then(()=>task(controller.signal)).finally(()=>{clearTimeout(timer);parentSignal?.removeEventListener('abort',abort)})}mark(id,ok,ms){let h=this.health.get(id)||{successCount:0,failureCount:0,averageResolveTime:0},count=h.successCount+h.failureCount;ok?h.successCount++:h.failureCount++;h.averageResolveTime=Math.round((h.averageResolveTime*count+ms)/(count+1));this.health.set(id,h)}priority(id){let base=(this.config.SOURCE_PRIORITY||[]).indexOf(id),h=this.health.get(id)||{};return (base<0?99:base)+(h.failureCount||0)*2-(h.successCount||0)*.1}
    async call(source,method,...args){let started=performance.now();try{let value=await this.withTimeout(signal=>source[method](...args,{signal}));this.mark(source.id,true,performance.now()-started);return value}catch(error){this.mark(source.id,false,performance.now()-started);throw error}}
    deduplicate(tracks){let groups=[];for(let track of tracks){let found=groups.find(x=>root.WaveTrackModel.isSameRecording(x.primary,track));if(!found){groups.push({primary:track,all:[track]});continue}found.all.push(track);found.all.sort((a,b)=>this.priority(a.source)-this.priority(b.source));found.primary=found.all[0]}return groups.map(({primary,all})=>({...primary,alternatives:all.filter(x=>x.id!==primary.id).map(x=>({...x,alternatives:[]}))}))}
    async aggregateBatch(method,args,onBatch){let key=`${method}:${JSON.stringify(args)}`,cached=this.metadataCache.get(key);if(cached&&cached.expiresAt>Date.now()){onBatch?.(cached.value);return cached.value}let settled=await Promise.allSettled(this.enabled().map(async source=>{const tracks=await this.call(source,method,...args);onBatch?.(tracks||[]);return tracks})),tracks=this.deduplicate(settled.filter(x=>x.status==='fulfilled').flatMap(x=>x.value||[]));this.metadataCache.set(key,{value:tracks,expiresAt:Date.now()+(this.config.METADATA_CACHE_TTL_MS||600000)});return tracks}
    aggregate(method,...args){return this.aggregateBatch(method,args,null)}
    buildSearchQueries(query){
      let exact=String(query||'').trim().replace(/\s+/g,' '),simple=exact.replace(/\b(?:ft|feat|featuring)\.?\s+[^[(\-–—]+/gi,' ').replace(/[([](?:official(?: audio| video)?|lyrics?|remix|remastered?)[^\])]*[\])]/gi,' ').replace(/\s+/g,' ').trim(),dictionary={мияги:'Miyagi',miyagi:'Miyagi',эдшпиль:'Endspiel',эндшпиль:'Endspiel',endspiel:'Endspiel'};
      let translit=exact.split(/\s+/).map(word=>dictionary[word.toLowerCase()]||word).join(' '),parts=simple.split(/\s+/),reversed=parts.length>2?`${parts.slice(-1)} ${parts.slice(0,-1).join(' ')}`:'';
      return [...new Set([exact,translit,simple,reversed].filter(Boolean))].slice(0,4);
    }
    async searchTracks(query){
      let queries=this.buildSearchQueries(query),sources=this.enabled(),settled=await Promise.allSettled(sources.map(async source=>{let attempts=await Promise.allSettled(queries.map(value=>this.call(source,'searchTracks',value))),tracks=this.deduplicate(attempts.filter(x=>x.status==='fulfilled').flatMap(x=>x.value||[]));console.log('SEARCH_SOURCE_RESULT',{source:source.label||source.id,count:tracks.length,queries});return tracks}));
      return this.deduplicate(settled.filter(x=>x.status==='fulfilled').flatMap(x=>x.value||[]));
    }
    async getCatalog({genres=[],onBatch=null}={}){let calls=[this.aggregateBatch('getTrendingTracks',[],onBatch),this.aggregateBatch('getLatestTracks',[],onBatch),...genres.slice(0,4).map(x=>this.aggregateBatch('getTracksByGenre',[x],onBatch))];return this.deduplicate((await Promise.allSettled(calls)).filter(x=>x.status==='fulfilled').flatMap(x=>x.value||[]))}
    async resolveTrack(track,{signal}={}){let variants=[track,...(track.alternatives||[])].sort((a,b)=>this.priority(a.source)-this.priority(b.source)),errors=[];for(let variant of variants){let key=`${variant.source}:${variant.sourceTrackId}`,cached=this.streamCache.get(key);if(cached&&(!cached.expiresAt||cached.expiresAt-(this.config.STREAM_CACHE_SAFETY_MS||30000)>Date.now()))return {...track,activeSource:variant.source,streamUrl:cached.url,stream:cached.url};let source=this.sources.get(variant.source);if(!source)continue;try{let resolved=await this.withTimeout(inner=>source.getStream(variant,{signal:inner}),this.config.REQUEST_TIMEOUT_MS||6000,signal);this.streamCache.set(key,{...resolved,resolvedAt:Date.now()});return {...track,activeSource:variant.source,streamUrl:resolved.url,stream:resolved.url}}catch(error){if(signal?.aborted)throw error;errors.push({source:variant.source,error:error.message})}}throw Object.assign(Error('No playable source for track'),{causes:errors})}debug(){return {priority:this.config.SOURCE_PRIORITY,health:Object.fromEntries(this.health),metadataCacheSize:this.metadataCache.size,streamCacheSize:this.streamCache.size}}
  }root.WaveSourceManager=SourceManager;
})(typeof window!=='undefined'?window:globalThis);
