(function(root){
  const VERSION_WORDS='live|remix|acoustic|cover|remaster(?:ed)?|instrumental|karaoke|demo',SERVICE_WORDS='official(?: audio| video)?|lyrics?|visuali[sz]er|hd|hq';
  function text(value){return String(value||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
  function clean(value,{keepVersions=true}={}){let out=text(value).replace(/\b(?:ft|feat|featuring)\.?\s+[^[(\-–—]+/gi,' ');out=out.replace(new RegExp(`\\((?:${SERVICE_WORDS})\\)|\\[(?:${SERVICE_WORDS})\\]`,'gi'),' ');if(!keepVersions)out=out.replace(new RegExp(`\\((?:${VERSION_WORDS})[^)]*\\)|\\[(?:${VERSION_WORDS})[^\\]]*\\]`,'gi'),' ');return out.replace(/[^a-z0-9а-яё]+/gi,' ').replace(/\s+/g,' ').trim()}
  function version(value){let match=text(value).match(new RegExp(`\\b(${VERSION_WORDS})\\b`,'i'));return match?match[1].replace('remastered','remaster'):''}
  function normalizeTrack(raw={},source=raw.source||'unknown'){let sourceTrackId=String(raw.sourceTrackId??raw.id??''),tags=Array.isArray(raw.tags)?raw.tags:String(raw.tags||'').split(',').map(x=>x.trim()).filter(Boolean),genreData=root.WaveGenre?.normalizeGenre(raw.rawGenre??raw.genre,tags,{title:raw.title,artist:raw.artist||raw.user?.name,language:raw.language,locale:raw.locale,country:raw.country})||{rawGenre:raw.genre??null,normalizedGenre:'unknown',subgenres:[],genreConfidence:raw.genre?1:0};return {id:raw.id&&String(raw.id).includes(':')?String(raw.id):`${source}:${sourceTrackId}`,source,sourceTrackId,title:raw.title||'Без названия',artist:raw.artist||raw.user?.name||'Неизвестный исполнитель',album:raw.album??raw.album_name??null,genre:raw.genre??genreData.rawGenre,genres:Array.isArray(raw.genres)?raw.genres.filter(Boolean):raw.genre?[raw.genre]:[],...genreData,mood:raw.mood??null,moodFeatures:raw.moodFeatures??null,moodConfidence:raw.moodConfidence??null,tags,artwork:typeof raw.artwork==='string'?raw.artwork:raw.artwork?.['480x480']||raw.artwork?.['150x150']||null,duration:Number(raw.duration)||null,releaseDate:raw.releaseDate??raw.release_date??null,bpm:Number(raw.bpm??raw.tempo)||null,tempo:Number(raw.bpm??raw.tempo)||null,energy:Number.isFinite(+raw.energy)?+raw.energy:null,valence:Number.isFinite(+raw.valence)?+raw.valence:null,danceability:Number.isFinite(+raw.danceability)?+raw.danceability:null,instrumental:Number.isFinite(+raw.instrumental)?+raw.instrumental:null,acoustic:Number.isFinite(+raw.acoustic)?+raw.acoustic:null,streamUrl:raw.streamUrl??raw.stream??null,stream:raw.streamUrl??raw.stream??'',permalink:raw.permalink??raw.permalink_url??null,alternatives:Array.isArray(raw.alternatives)?raw.alternatives:[],reason:raw.reason??raw._reason??'Подобрано для тебя',color:raw.color};}
  function same(a,b){if(clean(a.artist)!==clean(b.artist)||clean(a.title)!==clean(b.title)||version(a.title)!==version(b.title))return false;if(a.duration&&b.duration&&Math.abs(a.duration-b.duration)>4)return false;if(a.album&&b.album&&clean(a.album)!==clean(b.album))return false;if(a.releaseDate&&b.releaseDate&&String(a.releaseDate).slice(0,4)!==String(b.releaseDate).slice(0,4))return false;return true;}
  root.WaveTrackModel={normalizeTrack,normalizeComparable:clean,dedupeKey:track=>`${clean(track.artist)}|${clean(track.title)}|${version(track.title)}`,isSameRecording:same};
})(typeof window!=='undefined'?window:globalThis);
